### ISSUE TITLE
wolfssl 5.4 bug

### ISSUE THREAD

**Issue by openips** [openwrt/openwrt#10324]
when i build a rom in openwrt x64 master tree with curl and wolfssl 5.4 ,then i find curl can not work with https. i build a now one with openssl or wolfssl 5.3.0-stable , all are work well .
check and fix bugs, thks

**Comment by openips** [comment]
@[cotequeiroz](https://github.com/cotequeiroz)

**Comment by BKPepe** [comment]
Already reported here: https://github.com/openwrt/openwrt/issues/10302

Fixed by https://github.com/openwrt/packages/pull/19008

**Comment by openips** [comment]
the main bug is wolfssl 5.4 . only change default SSL to mbedTLS in curl can not fixed the wolfssl 5.4  bug

**Comment by openips** [comment]
I change default SSL to openssl in curl can also let curl work well .

**Comment by openips** [comment]
the wolfssl is a very importent lib in openwrt base system
the wolfssl 5.4 bug effect is very bad

**Comment by Borromini** [comment]
This is a dupe of https://github.com/openwrt/openwrt/issues/10311.

**Comment by BKPepe** [comment]
Not exactly, the issue, which you referenced is different than this.

**Comment by Borromini** [comment]
You're right. The overly generic issue title lead me down the wrong path.

**Comment by basha318i** [comment]
Having the same issue, had to switch to snapshot to get libcurl4 installing properly. I hope this dependency gets resolved soon.

**Comment by nberlee** [comment]
`wpad-wolfssl` also depends on a non existing wolfssl 5.4 library

**Comment by borkra** [comment]
https://github.com/openwrt/openwrt/pull/10322

**Comment by Neustradamus** [comment]
To follow this ticket.
