### ISSUE TITLE
Interface option network.wan6.sourcefilter='0' is ignored

### ISSUE THREAD

**Issue by jorti** [openwrt/openwrt#14954]
### Describe the bug

I'm configuring IPv6 masquerading as [described in the wiki](https://openwrt.org/docs/guide-user/network/ipv6/ipv6.nat6), however setting the option `network.wan6.sourcefilter='0'` does not appear to have any effect as the default IPv6 route still have a "from" restriction:

```
# uci show network.wan6
network.wan6=interface
network.wan6.proto='dhcpv6'
network.wan6.reqaddress='try'
network.wan6.reqprefix='auto'
network.wan6.device='wan.20'
network.wan6.norelease='1'
network.wan6.sourcefilter='0'  <-----

# uci show network.wan
network.wan=interface
network.wan.proto='pppoe'
network.wan.device='wan.20'
network.wan.username='username'
network.wan.password='password'
network.wan.ipv6='auto'

# uci show firewall.@zone[6]
firewall.cfg46dc81=zone
firewall.cfg46dc81.name='wan'
firewall.cfg46dc81.output='ACCEPT'
firewall.cfg46dc81.masq='1'
firewall.cfg46dc81.mtu_fix='1'
firewall.cfg46dc81.input='DROP'
firewall.cfg46dc81.forward='DROP'
firewall.cfg46dc81.network='wan' 'wan6'
firewall.cfg46dc81.masq6='1' <----

# ip -6 route show dev pppoe-wan
default from 2001:0db8:8403:1e00::/56 via fe80::1 dev pppoe-wan  metric 512  <---
default from 2001:0db8:84ff:ffff::4f75:2050 via fe80::1 dev pppoe-wan  metric 512 <---
fe80::1 dev pppoe-wan  metric 256 
fe80::4f75:2050 dev pppoe-wan  metric 256 
multicast ff00::/8 dev pppoe-wan  metric 256 
```

The effects are that the hosts in the dmz network (which only have a ULA prefix) cannot access external IPv6 addresses.

### OpenWrt version

r23630-842932a63d

### OpenWrt release

23.05.2

### OpenWrt target/subtarget

mediatek/mt7622

### Device

Linksys E8450 (UBI)

### Image kind

Official downloaded image

### Steps to reproduce

1. Set masq6 in WAN zone:
```
uci set firewall.@zone[1].masq6="1"
uci commit firewall
service firewall restart
```

2. Disable source filter in WAN6 interface:
```
uci set network.wan6.sourcefilter="0"
uci commit network
service network restart
```

3. Assign only ULA prefixes in internal dmz network:
```
uci set network.dmz.ip6class="local"
uci commit network
service network restart
```

4. Announce default route in internal dmz network:
```
uci set dhcp.dmz.ra_default="1"
uci commit dhcp
service odhcpd restart
```

### Actual behaviour

Default IPv6 routes have a "from" rescriction:

```
# ip -6 route show dev pppoe-wan | grep default
default from 2001:0db8:8403:1e00::/56 via fe80::1 dev pppoe-wan  metric 512
default from 2001:0db8:84ff:ffff::4f75:2050 via fe80::1 dev pppoe-wan  metric 512
```

### Expected behaviour

No source filter in the IPv6 routes. They should be something like this:

```
# ip -6 route show dev pppoe-wan | grep default
default via fe80::1 dev pppoe-wan  metric 512
default via fe80::1 dev pppoe-wan  metric 512
```

### Additional info

The underlying WAN device uses PPPoE.

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by brada4** [comment]
src is source address preferred, absolutely required if there is no address on interface (like often case that pppoe tunnel inner and outer has same IP)

**Comment by ptpt52** [comment]
PR https://github.com/openwrt/openwrt/pull/14466 should fix this issue

**Comment by therealjflf** [comment]
Unfortunately that issue still exists in the current stable release. My setup is almost exactly identical to the OP, the main difference being that my uplink is a wifi client. I have followed the same documentation in the OpenWRT documentation.

```
# cat /etc/openwrt_release 
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='25.12.1'
DISTRIB_REVISION='r32768-b21cfa8f8c'
DISTRIB_TARGET='ath79/generic'
DISTRIB_ARCH='mips_24kc'
DISTRIB_DESCRIPTION='OpenWrt 25.12.1 r32768-b21cfa8f8c'
DISTRIB_TAINTS=''
```

```
# echo dhcp.lan.ra_default firewall.@zone[1] network.lan.ip6class network.wan6.sourcefilter | xargs -n 1 uci show
dhcp.lan.ra_default='1'

firewall.cfg03dc81=zone
firewall.cfg03dc81.name='wan'
firewall.cfg03dc81.input='REJECT'
firewall.cfg03dc81.output='ACCEPT'
firewall.cfg03dc81.forward='DROP'
firewall.cfg03dc81.masq='1'
firewall.cfg03dc81.network='trm_wwan' 'trm_wwan6' 'wan' 'wan6'
firewall.cfg03dc81.masq6='1'

network.lan.ip6class='local'

network.wan6.sourcefilter='0'
```

And same thing, `network.wan6.sourcefilter` is ignored and the default routes are set up with source constraints:

```
# ip -6 route show default dev phy1-sta0
default from 2a02:908:1514:89a0:e64c:90c0:cc87:6599 via fe80::10:18ff:fe3f:50f4 proto static metric 512 pref medium
default from 2a02:908:1514:89a0::/64 via fe80::10:18ff:fe3f:50f4 proto static metric 512 pref medium
```

The result is the same, machines on the local IPv6 subnet cannot access the internet.

**Comment by jorti** [comment]
It works for me in OpenWrt 25.12.1, however I have to set `sourcefilter='0'` for both the wan (PPPoE) and wan6 (DHCPv6) interfaces. This looks odd but works:

```
# uci show network.wan
network.wan=interface
network.wan.proto='pppoe'
network.wan.device='wan.20'
network.wan.username='REDACTED'
network.wan.password='REDACTED'
network.wan.ipv6='auto'
network.wan.sourcefilter='0'

# uci show network.wan6
network.wan6=interface
network.wan6.proto='dhcpv6'
network.wan6.reqaddress='try'
network.wan6.reqprefix='auto'
network.wan6.device='wan.20'
network.wan6.norelease='1'
network.wan6.sourcefilter='0'

# ip -6 route show default dev pppoe-wan
default via fe80::1 proto static metric 512 pref medium
```

**Comment by therealjflf** [comment]
Thanks @jorti for confirming that it works. It turned out to be a PEBKAC error.

I'm using Travelmate on that router, and Travelmate creates its own upstream interfaces: `trm_wwan` and `trm_wwan6`. I was trying to disable sourcefilter on `wan6`, which isn't used ATM, and wondering why it didn't work on the `trm_wwan6` link... :facepalm:

Disabling sourcefilter on `trm_wwan6` was enough to fix the problem.

```
uci set network.trm_wwan6.sourcefilter=0
```
