### ISSUE TITLE
OpenWRT 24.10: package/kernel/mac80211 failed to build (build variant: regular)

### ISSUE THREAD

**Issue by ZerBea** [openwrt/openwrt#16905]
### Describe the bug

Building firmware for target bcm2708 failed with "package/kernel/mac80211 failed to build (build variant: regular)"
```
/home/zerobeat/Source/raspberry/openwrt/build_dir/target-arm_arm1176jzf-s+vfp_musl_eabi/linux-bcm27xx_bcm2708/mac80211-regular/backports-6.11.2/net/wireless/nl80211.c:18038:9: error: too many arguments to function 'genlmsg_multicast_allns'
18038 |         genlmsg_multicast_allns(&nl80211_fam, msg, 0,
      |         ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/zerobeat/Source/raspberry/openwrt/build_dir/target-arm_arm1176jzf-s+vfp_musl_eabi/linux-bcm27xx_bcm2708/mac80211-regular/backports-6.11.2/backport-include/net/genetlink.h:3,
                 from /home/zerobeat/Source/raspberry/openwrt/build_dir/target-arm_arm1176jzf-s+vfp_musl_eabi/linux-bcm27xx_bcm2708/mac80211-regular/backports-6.11.2/net/wireless/nl80211.c:25:
./include/net/genetlink.h:484:5: note: declared here
  484 | int genlmsg_multicast_allns(const struct genl_family *family,
      |     ^~~~~~~~~~~~~~~~~~~~~~~
/home/zerobeat/Source/raspberry/openwrt/build_dir/target-arm_arm1176jzf-s+vfp_musl_eabi/linux-bcm27xx_bcm2708/mac80211-regular/backports-6.11.2/net/wireless/nl80211.c: In function 'nl80211_send_beacon_hint_event':
/home/zerobeat/Source/raspberry/openwrt/build_dir/target-arm_arm1176jzf-s+vfp_musl_eabi/linux-bcm27xx_bcm2708/mac80211-regular/backports-6.11.2/net/wireless/nl80211.c:18774:9: error: too many arguments to function 'genlmsg_multicast_allns'
18774 |         genlmsg_multicast_allns(&nl80211_fam, msg, 0,
      |         ^~~~~~~~~~~~~~~~~~~~~~~
./include/net/genetlink.h:484:5: note: declared here
  484 | int genlmsg_multicast_allns(const struct genl_family *family,
      |     ^~~~~~~~~~~~~~~~~~~~~~~
make[9]: *** [scripts/Makefile.build:243: /home/zerobeat/Source/raspberry/openwrt/build_dir/target-arm_arm1176jzf-s+vfp_musl_eabi/linux-bcm27xx_bcm2708/mac80211-regular/backports-6.11.2/net/wireless/nl80211.o] Error 1
make[8]: *** [scripts/Makefile.build:480: /home/zerobeat/Source/raspberry/openwrt/build_dir/target-arm_arm1176jzf-s+vfp_musl_eabi/linux-bcm27xx_bcm2708/mac80211-regular/backports-6.11.2/net/wireless] Error 2
make[7]: *** [Makefile:1921: /home/zerobeat/Source/raspberry/openwrt/build_dir/target-arm_arm1176jzf-s+vfp_musl_eabi/linux-bcm27xx_bcm2708/mac80211-regular/backports-6.11.2] Error 2
make[6]: *** [Makefile.build:13: modules] Error 2
make[5]: *** [Makefile.real:105: modules] Error 2
make[4]: *** [Makefile:121: modules] Error 2
make[3]: *** [Makefile:402: /home/zerobeat/Source/raspberry/openwrt/build_dir/target-arm_arm1176jzf-s+vfp_musl_eabi/linux-bcm27xx_bcm2708/mac80211-regular/backports-6.11.2/.built] Error 2
make[3]: Leaving directory '/home/zerobeat/Source/raspberry/openwrt/package/kernel/mac80211'
time: package/kernel/mac80211/regular/compile#2.09#0.60#2.65
    ERROR: package/kernel/mac80211 failed to build (build variant: regular).
make[2]: *** [package/Makefile:179: package/kernel/mac80211/compile] Error 1
make[2]: Leaving directory '/home/zerobeat/Source/raspberry/openwrt'
make[1]: *** [package/Makefile:173: /home/zerobeat/Source/raspberry/openwrt/staging_dir/target-arm_arm1176jzf-s+vfp_musl_eabi/stamp/.package_compile] Error 2
```

### OpenWrt version

openwrt-24.10 (git branch -a)

### OpenWrt release

openwrt-24.10 (git branch -a)

### OpenWrt target/subtarget

bcm27xx_bcm2708

### Device

nl80211

### Image kind

Self-built image

### Steps to reproduce

compile latest githead (openwrt-24.10) for target bcm2708.

### Actual behaviour

build failed (too many arguments to function 'genlmsg_multicast_allns'): 
```
/home/zerobeat/Source/raspberry/openwrt/build_dir/target-arm_arm1176jzf-s+vfp_musl_eabi/linux-bcm27xx_bcm2708/mac80211-regular/backports-6.11.2/net/wireless/nl80211.c:18038:9: error: too many arguments to function 'genlmsg_multicast_allns'
18038 |         genlmsg_multicast_allns(&nl80211_fam, msg, 0,
```

### Expected behaviour

successful build

### Additional info

build for 23.05 compiles flawless

### Diffconfig

```text
CONFIG_TARGET_bcm27xx=y
CONFIG_TARGET_bcm27xx_bcm2708=y
CONFIG_TARGET_bcm27xx_bcm2708_DEVICE_rpi=y
CONFIG_ATH_USER_REGD=y
# CONFIG_BRCMFMAC_SDIO is not set
CONFIG_DRIVER_11AX_SUPPORT=y
# CONFIG_KERNEL_BTRFS_FS_POSIX_ACL is not set
# CONFIG_KERNEL_CIFS_ACL is not set
# CONFIG_KERNEL_EXT4_FS_POSIX_ACL is not set
# CONFIG_KERNEL_EXT4_FS_SECURITY is not set
# CONFIG_KERNEL_F2FS_FS_POSIX_ACL is not set
# CONFIG_KERNEL_F2FS_FS_SECURITY is not set
# CONFIG_KERNEL_FS_POSIX_ACL is not set
# CONFIG_KERNEL_HFSPLUS_FS_POSIX_ACL is not set
# CONFIG_KERNEL_HFS_FS_POSIX_ACL is not set
# CONFIG_KERNEL_JFFS2_FS_POSIX_ACL is not set
# CONFIG_KERNEL_JFFS2_FS_SECURITY is not set
# CONFIG_KERNEL_JFS_POSIX_ACL is not set
# CONFIG_KERNEL_NET_L3_MASTER_DEV is not set
# CONFIG_KERNEL_NFS_ACL_SUPPORT is not set
CONFIG_KERNEL_PAGE_POOL=y
# CONFIG_KERNEL_REISER_FS_POSIX_ACL is not set
# CONFIG_KERNEL_TMPFS_POSIX_ACL is not set
# CONFIG_KERNEL_UBIFS_FS_SECURITY is not set
# CONFIG_KERNEL_XFS_POSIX_ACL is not set
# CONFIG_LUCI_CSSTIDY is not set
# CONFIG_LUCI_JSMIN is not set
CONFIG_PACKAGE_ATH_DFS=y
CONFIG_PACKAGE_MAC80211_DEBUGFS=y
CONFIG_PACKAGE_MAC80211_MESH=y
CONFIG_PACKAGE_ar=y
CONFIG_PACKAGE_ath9k-htc-firmware=y
CONFIG_PACKAGE_bash=y
CONFIG_PACKAGE_binutils=y
# CONFIG_PACKAGE_ca-bundle is not set
# CONFIG_PACKAGE_dnsmasq is not set
# CONFIG_PACKAGE_firewall4 is not set
CONFIG_PACKAGE_gcc=y
CONFIG_PACKAGE_hcxlabtool=y
CONFIG_PACKAGE_kmod-ath=y
CONFIG_PACKAGE_kmod-ath9k-common=y
CONFIG_PACKAGE_kmod-ath9k-htc=y
CONFIG_PACKAGE_kmod-crypto-aead=y
CONFIG_PACKAGE_kmod-crypto-ccm=y
CONFIG_PACKAGE_kmod-crypto-cmac=y
CONFIG_PACKAGE_kmod-crypto-ctr=y
CONFIG_PACKAGE_kmod-crypto-gcm=y
CONFIG_PACKAGE_kmod-crypto-geniv=y
CONFIG_PACKAGE_kmod-crypto-gf128=y
CONFIG_PACKAGE_kmod-crypto-ghash=y
CONFIG_PACKAGE_kmod-crypto-hmac=y
CONFIG_PACKAGE_kmod-crypto-manager=y
CONFIG_PACKAGE_kmod-crypto-null=y
CONFIG_PACKAGE_kmod-crypto-rng=y
CONFIG_PACKAGE_kmod-crypto-seqiv=y
CONFIG_PACKAGE_kmod-crypto-sha256=y
CONFIG_PACKAGE_kmod-crypto-sha3=y
CONFIG_PACKAGE_kmod-crypto-sha512=y
CONFIG_PACKAGE_kmod-fs-configfs=y
CONFIG_PACKAGE_kmod-fs-ext4=y
CONFIG_PACKAGE_kmod-hwmon-core=y
CONFIG_PACKAGE_kmod-lib-crc16=y
CONFIG_PACKAGE_kmod-mac80211=y
CONFIG_PACKAGE_kmod-mii=y
CONFIG_PACKAGE_kmod-mt76-connac=y
CONFIG_PACKAGE_kmod-mt76-core=y
CONFIG_PACKAGE_kmod-mt76-usb=y
CONFIG_PACKAGE_kmod-mt7601u=y
CONFIG_PACKAGE_kmod-mt76x0-common=y
CONFIG_PACKAGE_kmod-mt76x02-common=y
CONFIG_PACKAGE_kmod-mt76x02-usb=y
CONFIG_PACKAGE_kmod-mt76x0u=y
CONFIG_PACKAGE_kmod-mt76x2-common=y
CONFIG_PACKAGE_kmod-mt76x2u=y
CONFIG_PACKAGE_kmod-mt7921-common=y
CONFIG_PACKAGE_kmod-mt7921-firmware=y
CONFIG_PACKAGE_kmod-mt7921u=y
CONFIG_PACKAGE_kmod-mt792x-common=y
CONFIG_PACKAGE_kmod-mt792x-usb=y
# CONFIG_PACKAGE_kmod-nf-conntrack is not set
# CONFIG_PACKAGE_kmod-nf-conntrack6 is not set
# CONFIG_PACKAGE_kmod-nf-flow is not set
# CONFIG_PACKAGE_kmod-nf-log is not set
# CONFIG_PACKAGE_kmod-nf-log6 is not set
# CONFIG_PACKAGE_kmod-nf-nat is not set
# CONFIG_PACKAGE_kmod-nf-reject is not set
# CONFIG_PACKAGE_kmod-nf-reject6 is not set
# CONFIG_PACKAGE_kmod-nfnetlink is not set
# CONFIG_PACKAGE_kmod-nft-core is not set
# CONFIG_PACKAGE_kmod-nft-fib is not set
# CONFIG_PACKAGE_kmod-nft-nat is not set
# CONFIG_PACKAGE_kmod-nft-offload is not set
# CONFIG_PACKAGE_kmod-ppp is not set
CONFIG_PACKAGE_kmod-random-core=y
CONFIG_PACKAGE_kmod-rt2800-lib=y
CONFIG_PACKAGE_kmod-rt2800-usb=y
CONFIG_PACKAGE_kmod-rt2x00-lib=y
CONFIG_PACKAGE_kmod-rt2x00-usb=y
CONFIG_PACKAGE_kmod-rtl8xxxu=y
# CONFIG_PACKAGE_kmod-sound-core is not set
CONFIG_PACKAGE_kmod-usb-net=y
CONFIG_PACKAGE_kmod-usb-net-cdc-ether=y
CONFIG_PACKAGE_kmod-usb-net-cdc-ncm=y
CONFIG_PACKAGE_kmod-usb-net-rtl8152=y
CONFIG_PACKAGE_libbfd=y
CONFIG_PACKAGE_libctf=y
CONFIG_PACKAGE_libncurses=y
# CONFIG_PACKAGE_libnftnl is not set
CONFIG_PACKAGE_libnl=y
CONFIG_PACKAGE_libnl-cli=y
CONFIG_PACKAGE_libnl-core=y
CONFIG_PACKAGE_libnl-genl=y
CONFIG_PACKAGE_libnl-nf=y
CONFIG_PACKAGE_libnl-route=y
CONFIG_PACKAGE_libopcodes=y
CONFIG_PACKAGE_libpcap=y
CONFIG_PACKAGE_libreadline=y
CONFIG_PACKAGE_libstdcpp=y
CONFIG_PACKAGE_libzstd=y
# CONFIG_PACKAGE_logd is not set
CONFIG_PACKAGE_mt7601u-firmware=y
# CONFIG_PACKAGE_mtd is not set
CONFIG_PACKAGE_nano=y
# CONFIG_PACKAGE_nftables-json is not set
CONFIG_PACKAGE_objdump=y
# CONFIG_PACKAGE_odhcp6c is not set
# CONFIG_PACKAGE_odhcpd-ipv6only is not set
# CONFIG_PACKAGE_partx-utils is not set
# CONFIG_PACKAGE_ppp is not set
# CONFIG_PACKAGE_procd-ujail is not set
CONFIG_PACKAGE_r8152-firmware=y
CONFIG_PACKAGE_rt2800-usb-firmware=y
CONFIG_PACKAGE_rtl8188eu-firmware=y
CONFIG_PACKAGE_rtl8188fu-firmware=y
CONFIG_PACKAGE_rtl8192ce-firmware=y
CONFIG_PACKAGE_rtl8192cu-firmware=y
CONFIG_PACKAGE_rtl8192de-firmware=y
CONFIG_PACKAGE_rtl8192du-firmware=y
CONFIG_PACKAGE_rtl8192eu-firmware=y
CONFIG_PACKAGE_rtl8192se-firmware=y
CONFIG_PACKAGE_terminfo=y
# CONFIG_PACKAGE_wpad-basic-mbedtls is not set
CONFIG_PACKAGE_zlib=y
# CONFIG_TARGET_EXT4_JOURNAL is not set
CONFIG_TARGET_KERNEL_PARTSIZE=128
CONFIG_TARGET_ROOTFS_PARTSIZE=2048
# CONFIG_TARGET_ROOTFS_SQUASHFS is not set
# CONFIG_USE_FS_ACL_ATTR is not set
CONFIG_ZSTD_OPTIMIZE_O3=y
CONFIG_PACKAGE_jansson=y
CONFIG_PACKAGE_kmod-lib-crc32c=y
CONFIG_PACKAGE_kmod-mmc=y
CONFIG_PACKAGE_libmnl=y
CONFIG_PACKAGE_libsmartcols=y
CONFIG_PACKAGE_ucode-mod-uloop=y
```

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by ZerBea** [comment]
I switched to the master branch and mac80211 compiles fine:
```
 make[3] -C package/network/config/wifi-scripts compile
 make[3] -C package/kernel/mac80211 compile
 make[3] -C package/libs/ncurses compile
```

**Comment by namiltd** [comment]
Fixed: https://github.com/openwrt/openwrt/commit/4b413687e68084d2c81472ae40eaa7d15e89c37b

**Comment by ZerBea** [comment]
Thanks.

**Comment by ZerBea** [comment]
After a git pull the issue is back. Beside 24.10 branch, now the master is affected too.

**Comment by namiltd** [comment]
I generated the ramips/mt7620 image from github 24.10 branch two hours ago and the problem didn't occur.

**Comment by ZerBea** [comment]
I'll do a fresh git pull and retry to compile it.

**Comment by ZerBea** [comment]
Ok, I see:
 ...nlmsg_multicast_allns-build-error-on-kernel-6.6.59.patch | 169 ++++++++++++++++++++++++++

**Comment by ZerBea** [comment]
Ok, both branches compiling fine again:
 make[3] -C package/network/config/wifi-scripts compile
 make[3] -C package/kernel/mac80211 compile
 make[3] -C package/libs/ncurses compile

Again, thanks.
