### ISSUE TITLE
A hardware acceleration issue potentially related to UDP multicast communication has been identified in IPTV multicast communication

### ISSUE THREAD

**Issue by ewangsoft** [openwrt/openwrt#18214]
### Describe the bug

This issue was observed on the GL.iNet GL-MT6000 (device details:  https://github.com/openwrt/openwrt/commit/fe10f9743935d6986e80e7cb082469e6bc5a03f0 ).

Under the OpenWrt 23.05 system, multicast proxy forwarding of China Unicom IPTV multicast video using omcproxy or igmpproxy worked normally. However, after upgrading to OpenWrt 24.10.0 and Snapshot versions, playback of China Unicom IPTV multicast video became choppy. The issue seemed to be resolved when the WAN interface speed was set to 100 Mbps.

### OpenWrt version

r28427-6df0e3d02a

### OpenWrt release

24.10.0

### OpenWrt target/subtarget

mediatek/filogic

### Device

GL.iNet GL-MT6000

### Image kind

Official downloaded image

### Steps to reproduce

**IGMP Proxy Configuration Parameters:**
config igmpproxy
	option quickleave 1
#	option verbose [0-3](none, minimal[default], more, maximum)

config phyint
	option network wan
	option zone wan
	option direction upstream
	list altnet 0.0.0.0/0

config phyint
	option network lan
	option zone lan
	option direction downstream

**/etc/config/network:**
config device
	option name 'br-lan'
	option type 'bridge'
	list ports 'lan1'
	list ports 'lan2'
	list ports 'lan3'
        list ports 'lan4'
	list ports 'lan5'
	option igmp_snooping '1'
config interface 'lan'
	option device 'br-lan'
	option proto 'static'
	option ipaddr '192.168.2.1'
	option netmask '255.255.255.0'
config device
	option type 'bridge'
	option name 'br-wan'
	list ports 'eth1'
	option igmp_snooping '1'
config interface 'wan'
	option device 'br-wan'
	option proto 'static'
	option ipaddr '192.168.1.6'
	option netmask '255.255.255.0'
	option gateway '192.168.1.1'

Then, open the IPTV multicast source link `udp://225.1.4.73:1102` using a media player on the terminal.

### Diffconfig

```text

```

### Terms

- [x] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by cocool97** [comment]
I have the same issue on a Xiaomi AX3000T, needed to downgrade to make it work

**Comment by ewangsoft** [comment]
the same issue on a H3C Magic NX30 Pro: (device details: https://github.com/openwrt/openwrt/commit/e78d1a06c8a47be9ea5a306bfb43f3d7ceb89646)

**Comment by possibly2** [comment]
Same issue with:
- Linksys WRT1900ACS
- BananaPI R3
- BananaPI R4

Reverted bsck to 23.05.05 for now.

**Comment by danpawlik** [comment]
I have same issue but with wifi calling (vowifi). Instead of reverting version, I switch to use software offload. Also it was acceptable, if hardware offload was enabled + qosify. With that combo, establishing connection takes longer comparing to sw offload, but was working.

**Comment by ewangsoft** [comment]
> I have same issue but with wifi calling (vowifi). Instead of reverting version, I switch to use software offload. Also it was acceptable, if hardware offload was enabled + qosify. With that combo, establishing connection takes longer comparing to sw offload, but was working.
> 
> Some useful links
> 
> * https://forum.openwrt.org/t/a-new-dual-10g-router-based-on-filogic-880-banana-pi-bpi-r4/163861/709
> * https://forum.openwrt.org/t/a-new-dual-10g-router-based-on-filogic-880-banana-pi-bpi-r4/163861/882
> * https://forum.openwrt.org/t/mt6000-custom-build-with-luci-and-some-optimization-kernel-6-6-x/185241/1715

I referred to the content in the third link to set it up, but the problem still persists.

**Comment by danpawlik** [comment]
Wondering, if by removing the 'udp' from https://github.com/openwrt/firewall4/blob/master/root/usr/share/firewall4/templates/ruleset.uc#L138 might help.

**Comment by ewangsoft** [comment]
Packet capture reveals that there are packet reordering and packet loss.

**Comment by ewangsoft** [comment]
The latest situation is that when the IPTV multicast video bitrate is 5Mbps, the video does not pixelate. However, when the IPTV multicast video bitrate is 10Mbps, the video does pixelate.

**Comment by mirtouf** [comment]
Release 24.10.1 has been made available and I am not sure the issue is fixed.
Did someone try with the new release?

**Comment by cocool97** [comment]
I took a look at the changelog and did not see anything related to our issue.. I'll try to update later on if nobody already did it

**Comment by ewangsoft** [comment]
> Release 24.10.1 has been made available and I am not sure the issue is fixed. Did someone reproduce the issue with the new release?

I have already tested it. The issue still persists under version 24.10.1.

**Comment by glassd00r** [comment]
UDP packet reordering when hw flow offload is enabled has been there since i started tinking with bpir4 (mt7988) from the onset.
What I do not know is if the reordering is due to the the hardware flow offloading process or that mtk ppe is reordering the packets.
I can confirm that UDP packets are not reordered when flow offload is disabled or when software flow offload is enable. Only when hardware flow offload is enabled does UDP packet reordering happens.
Thanks to @brada4 and this patch to fw4, I have been able to disable just UDP hw flow offloading.
With his patch [https://github.com/openwrt/firewall4/pull/22](url)
create /etc/nftables.d/20-custom-filter-chains.nft
`chain handle_offload {
  # ct bytes < 1000000 counter accept
  # ct packets < 30 counter accept
  meta l4proto udp counter accept
  # meta length < 100 counter accept
  # ct direction original counter accept
  # the fw4 offload table follows
  # flow add @ft accept
  # accept
}
`
@dangowrt @nbd168 @hauke

**Comment by brada4** [comment]
There was similar concern rised w r t gaming and mtk udp offload.

**Comment by ewangsoft** [comment]
> UDP packet reordering when hw flow offload is enabled has been there since i started tinking with bpir4 (mt7988) from the onset.
> 
> What I do not know is if the reordering is due to the the hardware flow offloading process or that mtk ppe is reordering the packets. I can confirm that UDP packets are not reordered when flow offload is disabled or when software flow offload is enable. Only when hardware flow offload is enabled does UDP packet reordering happens. Thanks to [@brada4](https://github.com/brada4) and this patch to fw4, I have been able to disable just UDP hw flow offloading. With his patch [https://github.com/openwrt/firewall4/pull/22](url) create /etc/nftables.d/20-custom-filter-chains.nft
> 
> ```
> chain handle_offload {
>   # ct bytes < 1000000 counter accept
>   # ct packets < 30 counter accept
>   meta l4proto udp counter accept
>   # meta length < 100 counter accept
>   # ct direction original counter accept
>   # the fw4 offload table follows
>   # flow add @ft accept
>   # accept
> }
> ```
> 
> [@dangowrt](https://github.com/dangowrt) [@nbd168](https://github.com/nbd168) [@hauke](https://github.com/hauke)



> UDP packet reordering when hw flow offload is enabled has been there since i started tinking with bpir4 (mt7988) from the onset.
> 
> What I do not know is if the reordering is due to the the hardware flow offloading process or that mtk ppe is reordering the packets. I can confirm that UDP packets are not reordered when flow offload is disabled or when software flow offload is enable. Only when hardware flow offload is enabled does UDP packet reordering happens. Thanks to [@brada4](https://github.com/brada4) and this patch to fw4, I have been able to disable just UDP hw flow offloading. With his patch [https://github.com/openwrt/firewall4/pull/22](url) create /etc/nftables.d/20-custom-filter-chains.nft
> 
> ```
> chain handle_offload {
>   # ct bytes < 1000000 counter accept
>   # ct packets < 30 counter accept
>   meta l4proto udp counter accept
>   # meta length < 100 counter accept
>   # ct direction original counter accept
>   # the fw4 offload table follows
>   # flow add @ft accept
>   # accept
> }
> ```
> 
> [@dangowrt](https://github.com/dangowrt) [@nbd168](https://github.com/nbd168) [@hauke](https://github.com/hauke)

Are you referring to the "hw flow offload" setting in the firewall configuration or the offload at the hardware driver level? If you're talking about the firewall setting, my router doesn't have it enabled.

**Comment by brada4** [comment]
Then what acceleration your title refers to?

**Comment by ewangsoft** [comment]
> Then what acceleration your title refers to?

I didn't use the offload in the firewall settings. Before raising this issue, I consulted a friend who works on customizing OpenWRT systems. I asked him how I should file an ISSUE, and he suggested that I do it this way. Here, it is suspected that...

**Comment by brada4** [comment]
You can always bridge tv or voice vlans to their voip and stb cpe-s without caring for protocols inside.

**Comment by brada4** [comment]
There is a known issue that hardware offload sometimes or always re-orders some datagrams around adding offload state.

**Comment by sashorion** [comment]
The same issue on a Xiaomi AX3000T + igmpproxy with any version 24.10.*, including 24.10.2.
Any options: NAT Offloading, Packet Steering and others do not affect this behavior.

"ethtool -K wan gro off" - solves the problem.

I discovered that UDP packets with size larger than 1316 (?) bytes are dropped between WAN and LAN.
http://www.noiro.mksat.net/tcpdump_ax3000t.png

**Comment by brada4** [comment]
Try leaving gro but disabling rx-gro-list only?

**Comment by sashorion** [comment]
> Try leaving gro but disabling rx-gro-list only?

ethtool -K wan gro on => The problem is showing up.
ethtool -K wan rx-gro-only off => Everything is fine, the problem does not appear.

**Comment by brada4** [comment]
For workaround - gro list disablement has minimal performance implications. 

Likely related:
https://github.com/openwrt/openwrt/issues/18608
@nbd168 may have some idea.

**Comment by cocool97** [comment]
I can confirm that on Xiaomi AX3000T with U-Boot layout the `ethtool -K wan rx-gro off` command fixes this issue. However I do not have access to `rx-gro-only` option

Does anyone know how to have this setting persistent through reboots ? It seems that it is lost when I reboot my device

**Comment by brada4** [comment]
@cocool97 the name of the option is `rx-gro-list`

**Comment by map-b** [comment]
Potential fix in snapshot has just been committed 604355e8c4d18dda22aeb618c1489c5369860418

**Comment by brada4** [comment]
@DragonBluep could you also cherry pick that for v24.10?

**Comment by sashorion** [comment]
> Does anyone know how to have this setting persistent through reboots ? It seems that it is lost when I reboot my device

Just add to /etc/rc.local (Local Startup in Luci)

sleep 5
ethtool -K wan rx-gro-list off

**Comment by kvic-z** [comment]
To summarise the discussion so far:

This tracker is mainly about multiple users observed issues that turned out to be caused by "rx-gro-list" being "on" by default. "**rx-gro-list**" is explicitly turned on by this OpenWrt patch "**600-net-enable-fraglist-GRO-by-default.patch**". Seems the patch should be removed. Users compiling their own OpenWrt can remove it from your local repo.

So it's not related to HW offload as the title may mislead people.

Except for @glassd00r who seems to see "out of order" UDP packets when the flow is offloaded to HW on MT7988A. But I think if "**receive side scaling (RSS)**" is working on his build, packets will always be processed in received order. Hence, no shuffling by the HW engine.

**Comment by glassd00r** [comment]
Resolved this some months back.
https://forum.openwrt.org/t/lets-talk-about-firewall4-default-nftables-firewall/231246/66

**Comment by ewangsoft** [comment]
> To summarise the discussion so far:
> 
> This tracker is mainly about multiple users observed issues that turned out to be caused by "rx-gro-list" being "on" by default. "**rx-gro-list**" is explicitly turned on by this OpenWrt patch "**600-net-enable-fraglist-GRO-by-default.patch**". Seems the patch should be removed. Users compiling their own OpenWrt can remove it from your local repo.
> 
> So it's not related to HW offload as the title may mislead people.
> 
> Except for [@glassd00r](https://github.com/glassd00r) who seems to see "out of order" UDP packets when the flow is offloaded to HW on MT7988A. But I think if "**receive side scaling (RSS)**" is working on his build, packets will always be processed in received order. Hence, no shuffling by the HW engine.

When I initially posted this ISSUE, I didn't realize the problem was related to GRO. Could you please suggest a more appropriate description for the ISSUE title? I'll update it accordingly.

> To summarise the discussion so far:
> 
> This tracker is mainly about multiple users observed issues that turned out to be caused by "rx-gro-list" being "on" by default. "**rx-gro-list**" is explicitly turned on by this OpenWrt patch "**600-net-enable-fraglist-GRO-by-default.patch**". Seems the patch should be removed. Users compiling their own OpenWrt can remove it from your local repo.
> 
> So it's not related to HW offload as the title may mislead people.
> 
> Except for [@glassd00r](https://github.com/glassd00r) who seems to see "out of order" UDP packets when the flow is offloaded to HW on MT7988A. But I think if "**receive side scaling (RSS)**" is working on his build, packets will always be processed in received order. Hence, no shuffling by the HW engine.

When I initially posted this ISSUE, I didn't realize the problem was related to GRO. Could you please suggest a more appropriate description for the ISSUE title? I'll update it accordingly.

**Comment by ewangsoft** [comment]
> To summarise the discussion so far:
> 
> This tracker is mainly about multiple users observed issues that turned out to be caused by "rx-gro-list" being "on" by default. "**rx-gro-list**" is explicitly turned on by this OpenWrt patch "**600-net-enable-fraglist-GRO-by-default.patch**". Seems the patch should be removed. Users compiling their own OpenWrt can remove it from your local repo.
> 
> So it's not related to HW offload as the title may mislead people.
> 
> Except for [@glassd00r](https://github.com/glassd00r) who seems to see "out of order" UDP packets when the flow is offloaded to HW on MT7988A. But I think if "**receive side scaling (RSS)**" is working on his build, packets will always be processed in received order. Hence, no shuffling by the HW engine.

When I initially posted this ISSUE, I didn't realize the problem was related to GRO. Could you please suggest a more appropriate description for the ISSUE title? I'll update it accordingly.

**Comment by brada4** [comment]
> no shuffling by the HW engine

Actually very predictable events of shuffling when CT state enters established from hw_offload on sysctl-able timer, next packet programs offload in slow path and few following packets may easily race past it.

**Comment by sashorion** [comment]
25.12.0 The problem still exists.
(Xiaomi AX3000T)
