### ISSUE TITLE
realtek: kernel 6.12 dumps during partition creation

### ISSUE THREAD

**Issue by plappermaul** [openwrt/openwrt#19014]
### Describe the bug

Hi,

I'm currently preparing the kernel 6.12 upgrade for Realtek devices. See https://github.com/openwrt/openwrt/pull/18935

I solved out all target specific issues except for this one. During boot up I get (some logging aded):

```
[    0.976635] Creating 8 MTD partitions on "spi0.0":
[    0.982169] 0x000000000000-0x000000080000 : "u-boot"
[    1.061134] u-boot: parser fixed-partitions: 0
[    1.066154] mtd_part_do_parse return with 0
[    1.070976] mtd_part_of_parse 6 return rc=0
[    1.075698] parse_mtd_partitions called mtd_part_of_parse rc=0
[    1.082320] parse_mtd_partitions return 0
[    1.086869] 0x000000080000-0x0000000c0000 : "u-boot-env"
[    1.130986] u-boot-env: parser fixed-partitions: 0
[    1.136395] mtd_part_do_parse return with 0
[    1.141205] mtd_part_of_parse 6 return rc=0
[    1.145923] parse_mtd_partitions called mtd_part_of_parse rc=0
[    1.152560] parse_mtd_partitions return 0
[    1.157111] 0x0000000c0000-0x000000100000 : "board-name"
[    1.201123] board-name: parser fixed-partitions: 0
[    1.206531] mtd_part_do_parse return with 0
[    1.211372] mtd_part_of_parse 6 return rc=0
[    1.216095] parse_mtd_partitions called mtd_part_of_parse rc=0
[    1.222729] parse_mtd_partitions return 0
[    1.227272] 0x000000100000-0x000000e80000 : "firmware"

[    1.290623] firmware: parser uimage-fw: -19 <--- mtdsplit fails

[    1.295367] mtd_part_do_parse return with -19
[    1.300239] mtd_part_of_parse 3 rc=-19
[    1.304658] firmware: parser fixed-partitions: 0
[    1.309857] mtd_part_do_parse return with 0
[    1.314648] mtd_part_of_parse 6 return rc=-19
[    1.319565] parse_mtd_partitions called mtd_part_of_parse rc=-19
[    1.326420] parse_mtd_partitions return -19
[    1.331251] Failed to parse subpartitions: -19
[    1.336258] Deleting MTD partitions on "spi0.0":
[    1.341525] Deleting u-boot MTD partition
[    1.346050] ------------[ cut here ]------------
[    1.351319] WARNING: CPU: 0 PID: 1 at block/genhd.c:668 del_mtd_blktrans_dev+0x34/0x128
[    1.360459] Modules linked in:
[    1.363933] CPU: 0 UID: 0 PID: 1 Comm: swapper Not tainted 6.12.31 #0
[    1.371148] Hardware name: D-Link DGS-1210-28
[    1.376026] Stack : 00000000 00000004 00000000 ffffffff 8182b82c 00000000 00000001 00000100
[    1.385509]         818343e8 808b09d0 80a1ddff 813e33a4 00000000 00000001 8182b7d8 3ffbebce
[    1.394978]         00000000 00000000 808b09d0 8182b710 ffffefff 00000000 ffffffea 00000074
[    1.404456]         8182b6d4 00000074 00000000 80993730 00000001 00000000 808b09d0 00000000
[    1.413933]         00000000 0000029c 81c6e2b8 00000003 00000018 804862d0 00000000 813e0000
[    1.423402]         ...
[    1.426166] Call Trace:
[    1.428902] [<801062e4>] show_stack+0x28/0xf0
[    1.433830] [<807b3a28>] dump_stack_lvl+0x48/0x7c
[    1.439125] [<80126b7c>] __warn+0x9c/0x118
[    1.443756] [<80126c54>] warn_slowpath_fmt+0x5c/0xac
[    1.449344] [<804c52f8>] del_mtd_blktrans_dev+0x34/0x128
[    1.455327] [<804c4e6c>] blktrans_notify_remove+0x80/0xc0
[    1.461400] [<804bc0d4>] del_mtd_device+0x5c/0xe8
[    1.466697] [<804be8a8>] __del_mtd_partitions+0xb8/0xf4
[    1.472576] [<804bfcf4>] del_mtd_partitions+0x48/0x6c
[    1.478260] [<804c003c>] add_mtd_partitions+0xb8/0x1dc
[    1.484041] [<804bfde4>] parse_mtd_partitions+0xcc/0x26c
[    1.490017] [<804bc284>] mtd_device_parse_register+0x124/0x294
[    1.496574] [<804d8ccc>] spi_nor_probe+0x268/0x2f8
[    1.501984] [<8049a7d4>] really_probe+0xd4/0x34c
[    1.507195] [<8049ad10>] driver_probe_device+0x48/0x110
[    1.513074] [<8049aea8>] __device_attach_driver+0xd0/0x118
[    1.519242] [<8049845c>] bus_for_each_drv+0x7c/0xc8


```

To make it short.

- The issue does not exist on 6.6
- It happens during parsing the firmware partition with mtdsplit parser "uimage-fw"

Need to investigate further.

### OpenWrt version

upgrade 6.12

### OpenWrt release

upgrade 6.12

### OpenWrt target/subtarget

realtek/rtl838x

### Device

D-Link DGS-1210

### Image kind

Official downloaded image

### Steps to reproduce

Boot kernel 6.12

### Actual behaviour

Kernel givs stack dump and does not mount partitions

### Expected behaviour

kernel should boot up normally.

### Diffconfig

```text

```

### Terms

- [x] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by plappermaul** [comment]
@namiltd @janh @bmork : You did chnages in the past to this area. Any idea?

**Comment by GoetzGoerisch** [comment]
@plappermaul not seeing this on HPE 1920-24G  JG924A with the commit f180aab9cf631e432886d6788824a7ebd49caddf
Do you want logs?

**Comment by plappermaul** [comment]
Explanation for the moment:

OpenWrt main partition is defined in DTS as

```
  partition@280000 {
    label = "firmware";
    compatible = "denx,uimage";
    reg = <0x00100000 0xd80000>;
  };
```

The device has not yet an valid OpenWrt image installed. **Im running my very first initramfs boot**. mtdsplit_uimage() fails with ENODEV error.


```
[    2.913656] mtdsplit_uimage: no uImage found in "firmware"
[    3.133849] Failed to parse subpartitions: -19
[    3.138881] Deleting MTD partitions on "spi0.0":
```

While this was no issue for 6.6 kernels 6.12 has added a sanity check with [this patch](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/drivers/mtd/mtdpart.c?h=v6.15&id=5c2f7727d437cd42033d13ebc8b3d74b9fe65712
)

```
-		parse_mtd_partitions(child, parts[i].types, NULL);
+		ret = parse_mtd_partitions(child, parts[i].types, NULL);
+		if (ret < 0) {
+			pr_err("Failed to parse subpartitions: %d\n", ret);
+			goto err_del_partitions;
+		}
```

That is not so nice especially if one wants to install OpenWrt on a new device. Where to go from here?

- Revert the above patch?
- Only print a warning in mtdsplit_uimage.c?

```
	if (uimage_size == 0) {
		pr_warn("no uImage found in \"%s\"\n", master->name);
	}
```

**Comment by plappermaul** [comment]
@john-tho I just saw your commit https://github.com/openwrt/openwrt/commit/ade045084bd3f86969eaf0b35234aaa01e430fe1 regarding the same issue.

So I think passing a info here should be fine. Or do you have additional info for me.

**Comment by bmork** [comment]
Ouch.  If this has been in mainline since v6.12 (or before?) then a revert might be difficult.

But after looking closer, I think we should try to amend it. The sanity check as it is now is wrong IMHO.  It should at least ignore ENODEV, which has always been normal and expected from parse_mtd_partitions().  This is like a USB device failing to probe.  You don't fail the USB bus when that happens, ignoring all other devices.  You skip the failing device and continue.

Bailing out for other errors, like ENOMEM, does make some sense.

**Comment by bmork** [comment]
Or maybe that ENODEV assumption was just wrong all the time?  I looked at the mainline examples, and see that for example
 drivers/mtd/parsers/ofpart_core.c has had
```
return 0; /* No partitions found */
```
since forever.  So maybe we should replace all ENODEV returns with 0 like you suggest.   Certainly smpler than arguing with upstream....   Not too sure about upping the debug printks to warnings.  Will that help or confuse users?  The parsing falures are expected most of the time they happen

**Comment by plappermaul** [comment]
Will be fixed with https://github.com/openwrt/openwrt/pull/19016

**Comment by bmork** [comment]
OK, but I believe this should go into  target/linux/generic/pending-6.12/400-mtd-mtdsplit-support.patch to catch every possibly instance of return -ENODEV.  The error handling there is a bit flaky.  It should probably break out of the loop on most errors, but ignore ENODEV.

```
+static int parse_mtd_partitions_by_type(struct mtd_info *master,
+                                       enum mtd_parser_type type,
+                                       const struct mtd_partition **pparts,
+                                       struct mtd_part_parser_data *data)
+{
+       struct mtd_part_parser *prev = NULL;
+       int ret = 0;
+
+       while (1) {
+               struct mtd_part_parser *parser;
+
+               parser = get_partition_parser_by_type(type, prev);
+               if (!parser)
+                       break;
+
+               ret = (*parser->parse_fn)(master, pparts, data);
+
+               if (ret > 0) {
+                       mtd_part_parser_put(parser);
+                       printk(KERN_NOTICE
+                              "%d %s partitions found on MTD device %s\n",
+                              ret, parser->name, master->name);
+                       break;
+               }
+
+               prev = parser;
+       }
+
+       return ret;
+}
+
+static int
+run_parsers_by_type(struct mtd_info *child, enum mtd_parser_type type)
+{
+       struct mtd_partition *parts;
+       int nr_parts;
+       int i;
+
+       nr_parts = parse_mtd_partitions_by_type(child, type, (const struct mtd_partition **)&parts,
+                                               NULL);
+       if (nr_parts <= 0)
+               return nr_parts;
+
+       if (WARN_ON(!parts))
+               return 0;
+
+       for (i = 0; i < nr_parts; i++) {
+               /* adjust partition offsets */
+               parts[i].offset += child->part.offset;
+
+               mtd_add_partition(child->parent,
+                                 parts[i].name,
+                                 parts[i].offset,
+                                 parts[i].size);
+       }
+
+       kfree(parts);
+
+       return nr_parts;
+}
```

We have a number of other mtd spltters returning -ENODEV:
```
bjorn@canardo:/usr/local/src/openwrt$ git grep -l ENODEV target/linux/generic/files/drivers/mtd/mtdsplit
target/linux/generic/files/drivers/mtd/mtdsplit/mtdsplit.c
target/linux/generic/files/drivers/mtd/mtdsplit/mtdsplit.h
target/linux/generic/files/drivers/mtd/mtdsplit/mtdsplit_elf.c
target/linux/generic/files/drivers/mtd/mtdsplit/mtdsplit_fit.c
target/linux/generic/files/drivers/mtd/mtdsplit/mtdsplit_jimage.c
target/linux/generic/files/drivers/mtd/mtdsplit/mtdsplit_seil.c
target/linux/generic/files/drivers/mtd/mtdsplit/mtdsplit_trx.c
target/linux/generic/files/drivers/mtd/mtdsplit/mtdsplit_uimage.c
```

I believe it makes sense to catch them all with a sinlge
```
       if (nr_parts == -ENODEV)
                  return 0;

```
in run_parsers_by_type()

**Comment by plappermaul** [comment]
As I have no time to test them all I will focus on exactly our use case.

**Comment by plappermaul** [comment]
Fixed with https://github.com/openwrt/openwrt/pull/19016

**Comment by Djfe** [comment]
this was not fixed for other instances of mtdsplit, was it?
let's leave the issue open then or should we open a new one?

**Comment by plappermaul** [comment]
Feel free to open a new issue. I currently can only report/fix what I have observed myself.
