### ISSUE TITLE
Something between 94f043b and 604355e breaks 2,4 GHz Wifi on ath9k device (TP-Link Archer C7 v5)

### ISSUE THREAD

**Issue by schuettecarsten** [openwrt/openwrt#19312]
### Describe the bug

Something between https://github.com/openwrt/openwrt/commit/94f043bf87de3aa16d45b40bcb7a186d03dd8016 and https://github.com/openwrt/openwrt/commit/604355e8c4d18dda22aeb618c1489c5369860418 breaks 2,4 GHz Wifi on ath9k device (TP-Link Archer C7 v5). I use ImageBuilder to create the image and only add some LuCI things to the image, nothing special. In the logs I can see that PHY for radio1 is not found for 604355e while the same config works fine on 94f043b. radio0 and 5 GHz Wifi works fine. Resetting wireless config did not help.

### OpenWrt version

r30266-94f043bf87

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

ath79/generic

### Device

TP-Link Archer C7 v5

### Image kind

Official downloaded image

### Diffconfig

```text

```

### Terms

- [x] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by danpawlik** [comment]
just FYI: it was mentioned in https://github.com/openwrt/openwrt/pull/18911

**Comment by schuettecarsten** [comment]
> just FYI: it was mentioned in [#18911](https://github.com/openwrt/openwrt/pull/18911)

Oh, thank you. I just looked for existing Issues and did not investigate the discussions at the closed PRs.

**Comment by danpawlik** [comment]
@schuettecarsten you can revert https://github.com/openwrt/openwrt/commit/2ac791e87d3d09f2bb07d99c54f85b34297d8678 and all should be fine.

**Comment by schuettecarsten** [comment]
> [@schuettecarsten](https://github.com/schuettecarsten) you can revert [2ac791e](https://github.com/openwrt/openwrt/commit/2ac791e87d3d09f2bb07d99c54f85b34297d8678) and all should be fine.

Yes, but this does not work if you use ImageBuilder to create your images. I switched from custom-compile to ImageBuilder some weeks ago, but it looks like building snapshot myself would be a better idea.

**Comment by grosjo** [comment]
Same problem here, latest git breaks ath9k

```
Sun Jul  6 17:23:08 2025 daemon.notice netifd: radio0 (2143): WARNING: Variable 'data' does not exist or is not an array/object                                             
Sun Jul  6 17:23:08 2025 daemon.notice netifd: radio0 (2143): Phy not found                                                                                                 
Sun Jul  6 17:23:08 2025 daemon.notice netifd: radio0 (2143): Could not find PHY for device 'radio0'                                                                        
Sun Jul  6 17:23:08 2025 daemon.notice netifd: Wireless device 'radio0' set retry=0                                                                                         
Sun Jul  6 17:23:08 2025 daemon.crit netifd: Wireless device 'radio0' setup failed, retry=0                                                                                 
Sun Jul  6 17:23:09 2025 daemon.notice netifd: radio0 (2198): WARNING: Variable 'data' does not exist or is not an array/object                                             
Sun Jul  6 17:23:09 2025 daemon.notice netifd: radio0 (2198): Bug: PHY is undefined for device 'radio0'                                                                     
Sun Jul  6 17:23:09 2025 daemon.notice netifd: Wireless device 'radio0' is now down             
```

**Comment by grosjo** [comment]
Earlier git worked fine

**Comment by grosjo** [comment]
I had to do 

`git reset --hard 39580b1d7bf4062238be26d85bcd33cf55464ee8`

to recover a working device

**Comment by schuettecarsten** [comment]
> Same problem here, latest git breaks ath9k

My log is the same.

**Comment by danpawlik** [comment]
It is enough to 
```
git revert 2ac791e87d3d09f2bb07d99c54f85b34297d8678
```

**Comment by grosjo** [comment]
Maybe shall we include @nbd168 and @AgustinLorenzo in this thread ?

**Comment by grosjo** [comment]
> It is enough to
> 
> ```
> git revert 2ac791e87d3d09f2bb07d99c54f85b34297d8678
> ```

No, it does not. Only the reset to the previous resolves the situation

**Comment by schuettecarsten** [comment]
> > It is enough to
> > ```
> > git revert 2ac791e87d3d09f2bb07d99c54f85b34297d8678
> > ```
> 
> No, it does not. Only the reset to the previous resolves the situation

Still testing and investigating, it seems that you need to revert https://github.com/openwrt/openwrt/commit/2ac791e87d3d09f2bb07d99c54f85b34297d8678 and https://github.com/openwrt/openwrt/commit/88f4c32060f79e5161a789e85da299cebbde68bf

**Comment by nbd168** [comment]
The hostapd issue should be fixed now. Looking into the ath9k regression next

**Comment by nbd168** [comment]
ath9k regression should be fixed in d2b2670937f051bda7c8fbda8a6c0131977d5e68, please test

**Comment by danpawlik** [comment]
works well @nbd168 thank you!

**Comment by oldium** [comment]
Perfect timing, guys. Thanks! Will test C7 v4/v5 after local rebuild :-)

**Comment by oldium** [comment]
Works fine. Thanks, Felix @nbd168 !

**Comment by grosjo** [comment]
Works for me as well, thanks

**Comment by schuettecarsten** [comment]
@nbd168 - sorry, but, it does *not* work on my devices.

Wireless on my devices with current version:

<img width="1211" height="400" alt="Image" src="https://github.com/user-attachments/assets/25b234e6-f959-491e-9d14-9c76b49e6fb5" />

<img width="1205" height="511" alt="Image" src="https://github.com/user-attachments/assets/1ad37882-d49b-4ee9-814e-091239d74da0" />

Wireless with version from 2025-07-04:

<img width="1208" height="281" alt="Image" src="https://github.com/user-attachments/assets/74083fe6-3bb3-40b8-b223-a3b87be6d924" />

<img width="1211" height="391" alt="Image" src="https://github.com/user-attachments/assets/c82166a5-b761-44fd-be8c-901c6fcdb725" />

**Comment by nbd168** [comment]
@schuettecarsten it seems that somebody broke it again for you, right after I fixed it. Please test 118d8ee98132f4519cc208cbbaae6d1f8cb7d295, it should work now.

**Comment by schuettecarsten** [comment]
@nbd168 Thank you, will test as soon as the ImageBuilder update is available

**Comment by schuettecarsten** [comment]
> @schuettecarsten it seems that somebody broke it again for you, right after I fixed it. Please test 118d8ee98132f4519cc208cbbaae6d1f8cb7d295, it should work now.

@nbd168 still no luck.

![Screenshot_20250710_052941_Edge.png](https://github.com/user-attachments/assets/8089a8f3-6421-4d20-8503-654810dcde6a)

**Comment by schuettecarsten** [comment]
@nbd168 works, thank you
