### ISSUE TITLE
ASU and Firmware Selector do not work for customized images for OpenWrt-23.05.6

### ISSUE THREAD

**Issue by Ro-1-2-3** [openwrt/openwrt#19885]
### Describe the bug

It’s been a week since the release of  OpenWrt-23.05.6, but none of the imagebuilder containers for its targets had yet been created (with the exception of ramips/mt7621 target, which was created manually, as a response to somebody’s open issue for that particular target).

As an example, the mediatek/filogic target container, is missing, so one gets errors when trying to build a 23.05.6 image with a custom package selection, both via router ASU and via Firmware Selector website.

### OpenWrt version

23.05.6

### OpenWrt release

23.05.6

### OpenWrt target/subtarget

All

### Device

All

### Image kind

Official downloaded image

### Steps to reproduce

![Image](https://github.com/user-attachments/assets/6527681c-53c7-4055-9091-a6a1007a09f6)

### Actual behaviour

See the error message on the above screenshot.

### Expected behaviour

Both ASU and OpenWrt Firmware Selector site are expected to generate customized images of the official release of OpenWrt-23.05.6.

### Diffconfig

```text

```

### Terms

- [x] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by robimarko** [comment]
I have triggered the 23.05.6 container builds, some failed but most suceeded so it should work now

**Comment by Ro-1-2-3** [comment]
I still see only Snapshots being built and posted in the past several days, and none of 23.05.6:

https://github.com/openwrt/docker/pkgs/container/imagebuilder/versions

**Comment by robimarko** [comment]
23.05.6 tagged images were pushed to ghcr and docker, look at the job logs.
And fw selector is now able to generate the images, so they were built and pushed (With the exception of those that failed to build)

**Comment by Ro-1-2-3** [comment]
Ok, trying right now for Mango router (GL.iNet GL-MT300N V2, ramips/mt76x8)...
Fails with an empty error message (pink box):

![Image](https://github.com/user-attachments/assets/33bf3c7e-e3a1-461e-a715-715e53228dba)

**Comment by robimarko** [comment]
Works for me

<img width="1118" height="1298" alt="Image" src="https://github.com/user-attachments/assets/308b704a-c524-45ee-9d76-b56ed21c7ee9" />

**Comment by Ro-1-2-3** [comment]
Yes, now it works indeed!
(My apologies for confusion - I accidentally pasted an extra junk simbol with my extra package list).

Thank you for your help, I really appreciate it!

(Should we close this issue then?)
