### ISSUE TITLE
OpenWRT One: No wifi with version OpenWrt SNAPSHOT r31180-86618df095

### ISSUE THREAD

**Issue by wom-bat** [openwrt/openwrt#20218]
### Describe the bug

It seems as though the iwinfo package is missing from the snapshot.  Manualy installing it fixes the problem.

### OpenWrt version

r31180-86618df095

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

mediatek/filogic

### Device

OpenWRT One

### Image kind

Official downloaded image

### Steps to reproduce

Flash the firmware; try to bring up the WiFi interfaces.

### Actual behaviour

The interfaces always show as 'disabled' in luci; and do not show up when i type `ip link` in the CLI.
logread shows:
```
daemon.notice netifd: radio0 (2152): ./mac80211.sh: eval: line 644: iwinfo: not found
daemon.notice netifd: radio0 (2152): Could not find PHY for device 'radio0'
```

### Additional info

Installing `iwinfo` from the packages directory fixes the issue; but I'd expect it to be part of the base image

### Diffconfig

```text

```

### Terms

- [x] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by hauke** [comment]
This should be fixed with https://github.com/openwrt/openwrt/pull/20211 in 878f31c2109d6d71d3e6e011f02bb7bf17a763fc

**Comment by efahl** [comment]
Seem you can fix it in the interim with `apk update && apk add iwinfo`  (https://forum.openwrt.org/t/owut-openwrt-upgrade-tool/200035/804).

**Comment by ttc0419** [comment]
iwinfo is still not selected for the base image when using the latest image builder:
```
Current Target: "mediatek/filogic"
Current Architecture: "aarch64"
Current Revision: "r31223-2f6a467f6c"

Building images for mediatek - Cudy TR3000 v1 (OpenWrt U-Boot layout)
Packages: apk-mbedtls base-files ca-bundle dnsmasq dropbear firewall4 fitblk fstools kernel kmod-crypto-hw-safexcel kmod-gpio-button-hotplug kmod-leds-gpio kmod-mt7915e kmod-mt7981-firmware kmod-nft-offload kmod-usb3 libc libgcc libustream-mbedtls logd mt7981-wo-firmware mtd netifd nftables odhcp6c odhcpd-ipv6only ppp ppp-mod-pppoe procd-ujail uboot-envtools uci uclient-fetch urandom-seed urngd wpad-basic-mbedtls

OK: 0 MiB in 0 packages

Installing packages...
(  1/129) Installing libgcc1 (14.3.0-r5)
(  2/129) Installing libc (1.2.5-r5)
(  3/129) Installing libmbedtls21 (3.6.4-r1)
(  4/129) Installing libubox20250723 (2025.07.23~49056d17-r1)
(  5/129) Installing libuclient20201210 (2024.10.22~88ae8f20-r1)
(  6/129) Installing uclient-fetch (2024.10.22~88ae8f20-r1)
(  7/129) Installing zlib (1.3.1-r1)
(  8/129) Installing apk-mbedtls (3.0.0_pre20250606-r2)
(  9/129) Installing busybox (1.37.0-r5)
( 10/129) Installing ubi-utils (2.2.1-r1)
( 11/129) Installing libubus20250702 (2025.07.02~5952b48e-r1)
( 12/129) Installing libuci20250120 (2025.08.14~9033e8c2-r1)
( 13/129) Installing libjson-c5 (0.18-r1)
( 14/129) Installing libblobmsg-json20250723 (2025.07.23~49056d17-r1)
( 15/129) Installing ubusd (2025.07.02~5952b48e-r1)
( 16/129) Installing ubus (2025.07.02~5952b48e-r1)
( 17/129) Installing ubox (2024.04.26~85f10530-r1)
( 18/129) Installing fstools (2025.07.05~e8cd820c-r1)
( 19/129) Installing fwtool (2019.11.12~8f7fe925-r1)
( 20/129) Installing jsonfilter (2025.04.18~8a86fb78-r1)
( 21/129) Installing jshn (2025.07.23~49056d17-r1)
( 22/129) Installing libnl-tiny1 (2025.03.19~c0df580a-r1)
( 23/129) Installing libudebug (2025.08.24~edeb4d6d)
( 24/129) Installing libucode20230711 (2025.08.26~5f712ffd-r1)
( 25/129) Installing ucode (2025.08.26~5f712ffd-r1)
( 26/129) Installing ucode-mod-fs (2025.08.26~5f712ffd-r1)
( 27/129) Installing ucode-mod-ubus (2025.08.26~5f712ffd-r1)
( 28/129) Installing ucode-mod-uci (2025.08.26~5f712ffd-r1)
( 29/129) Installing ucode-mod-uloop (2025.08.26~5f712ffd-r1)
( 30/129) Installing netifd (2025.09.12~2a85440b-r1)
( 31/129) Installing openwrt-keyring (2024.11.01~fbae29d7-r1)
( 32/129) Installing libjson-script20250723 (2025.07.23~49056d17-r1)
( 33/129) Installing procd (2025.08.12~dafdf98b-r1)
( 34/129) Installing procd-seccomp (2025.08.12~dafdf98b-r1)
( 35/129) Installing usign (2020.05.23~f1f65026-r1)
( 36/129) Installing base-files (1667~2f6a467f6c)
( 37/129) Installing ca-bundle (20250419-r1)
( 38/129) Installing dnsmasq (2.91-r2)
( 39/129) Installing dropbear (2025.88-r4)
( 40/129) Installing kernel (6.12.49~457143262baaa3b3c3261909ce3dcb61-r1)
( 41/129) Installing kmod-crypto-hash (6.12.49-r1)
( 42/129) Installing kmod-crypto-crc32c (6.12.49-r1)
( 43/129) Installing kmod-lib-crc32c (6.12.49-r1)
( 44/129) Installing kmod-nf-conntrack (6.12.49-r1)
( 45/129) Installing kmod-nf-conntrack6 (6.12.49-r1)
( 46/129) Installing kmod-nf-log (6.12.49-r1)
( 47/129) Installing kmod-nf-log6 (6.12.49-r1)
( 48/129) Installing kmod-nf-nat (6.12.49-r1)
( 49/129) Installing kmod-nf-reject (6.12.49-r1)
( 50/129) Installing kmod-nf-reject6 (6.12.49-r1)
( 51/129) Installing kmod-nfnetlink (6.12.49-r1)
( 52/129) Installing kmod-nft-core (6.12.49-r1)
( 53/129) Installing kmod-nft-fib (6.12.49-r1)
( 54/129) Installing kmod-nft-nat (6.12.49-r1)
( 55/129) Installing kmod-nf-flow (6.12.49-r1)
( 56/129) Installing kmod-nft-offload (6.12.49-r1)
( 57/129) Installing jansson4 (2.14-r3)
( 58/129) Installing libmnl0 (1.0.5-r1)
( 59/129) Installing libnftnl11 (1.3.0-r1)
( 60/129) Installing nftables-json (1.1.5-r1)
( 61/129) Installing firewall4 (2025.03.17~b6e51575-r1)
( 62/129) Installing fit-check-sign (2025.07-r1)
( 63/129) Installing fitblk (2)
( 64/129) Installing eip197-mini-firmware (20250917-r1)
( 65/129) Installing kmod-crypto-null (6.12.49-r1)
( 66/129) Installing kmod-crypto-aead (6.12.49-r1)
( 67/129) Installing kmod-crypto-manager (6.12.49-r1)
( 68/129) Installing kmod-crypto-authenc (6.12.49-r1)
( 69/129) Installing kmod-crypto-des (6.12.49-r1)
( 70/129) Installing kmod-crypto-hmac (6.12.49-r1)
( 71/129) Installing kmod-crypto-md5 (6.12.49-r1)
( 72/129) Installing kmod-crypto-sha1 (6.12.49-r1)
( 73/129) Installing kmod-crypto-sha256 (6.12.49-r1)
( 74/129) Installing kmod-crypto-sha512 (6.12.49-r1)
( 75/129) Installing kmod-crypto-hw-safexcel (6.12.49-r1)
( 76/129) Installing kmod-gpio-button-hotplug (6.12.49-r5)
( 77/129) Installing kmod-leds-gpio (6.12.49-r1)
( 78/129) Installing kmod-i2c-core (6.12.49-r1)
( 79/129) Installing kmod-hwmon-core (6.12.49-r1)
( 80/129) Installing hostapd-common (2025.08.26~ca266cc2-r1)
( 81/129) Installing iw (6.9-r4)
( 82/129) Installing ucode-mod-digest (2025.08.26~5f712ffd-r1)
( 83/129) Installing ucode-mod-nl80211 (2025.08.26~5f712ffd-r1)
( 84/129) Installing ucode-mod-rtnl (2025.08.26~5f712ffd-r1)
( 85/129) Installing wifi-scripts (1.0-r1)
( 86/129) Installing wireless-regdb (2025.07.10-r1)
( 87/129) Installing kmod-cfg80211 (6.12.49.6.16-r1)
( 88/129) Installing kmod-crypto-sha3 (6.12.49-r1)
( 89/129) Installing kmod-crypto-rng (6.12.49-r1)
( 90/129) Installing kmod-crypto-geniv (6.12.49-r1)
( 91/129) Installing kmod-crypto-seqiv (6.12.49-r1)
( 92/129) Installing kmod-crypto-ctr (6.12.49-r1)
( 93/129) Installing kmod-crypto-ccm (6.12.49-r1)
( 94/129) Installing kmod-crypto-cmac (6.12.49-r1)
( 95/129) Installing kmod-crypto-gf128 (6.12.49-r1)
( 96/129) Installing kmod-crypto-ghash (6.12.49-r1)
( 97/129) Installing kmod-crypto-gcm (6.12.49-r1)
( 98/129) Installing kmod-mac80211 (6.12.49.6.16-r1)
( 99/129) Installing kmod-mt76-core (6.12.49.2025.09.15~6467af3b-r1)
(100/129) Installing kmod-mt76-connac (6.12.49.2025.09.15~6467af3b-r1)
(101/129) Installing kmod-thermal (6.12.49-r1)
(102/129) Installing kmod-mt7915e (6.12.49.2025.09.15~6467af3b-r1)
(103/129) Installing kmod-mt7981-firmware (6.12.49.2025.09.15~6467af3b-r1)
(104/129) Installing kmod-nls-base (6.12.49-r1)
(105/129) Installing kmod-usb-common (6.12.49-r1)
(106/129) Installing kmod-usb-core (6.12.49-r1)
(107/129) Installing kmod-usb-xhci-hcd (6.12.49-r1)
(108/129) Installing kmod-usb-xhci-mtk (6.12.49-r1)
(109/129) Installing kmod-usb3 (6.12.49-r1)
(110/129) Installing libustream-mbedtls20201210 (2024.07.28~99bd3d2b-r1)
(111/129) Installing logd (2024.04.26~85f10530-r1)
(112/129) Installing mt7981-wo-firmware (20250917-r1)
(113/129) Installing mtd (26)
(114/129) Installing odhcp6c (2025.02.06~8aa8b706-r1)
(115/129) Installing odhcpd-ipv6only (2025.09.27~bc9f9d93-r1)
(116/129) Installing kmod-lib-crc-ccitt (6.12.49-r1)
(117/129) Installing kmod-slhc (6.12.49-r1)
(118/129) Installing kmod-ppp (6.12.49-r1)
(119/129) Installing ppp (2.5.2-r2)
(120/129) Installing kmod-pppox (6.12.49-r1)
(121/129) Installing kmod-pppoe (6.12.49-r1)
(122/129) Installing ppp-mod-pppoe (2.5.2-r2)
(123/129) Installing procd-ujail (2025.08.12~dafdf98b-r1)
(124/129) Installing uboot-envtools (2025.07-r1)
(125/129) Installing uci (2025.08.14~9033e8c2-r1)
(126/129) Installing getrandom (2024.04.26~85f10530-r1)
(127/129) Installing urandom-seed (3)
(128/129) Installing urngd (2023.11.01~44365eb1-r1)
(129/129) Installing wpad-basic-mbedtls (2025.08.26~ca266cc2-r1)
OK: 21 MiB in 129 packages
```

**Comment by diizzyy** [comment]
Still broken with recent checkout, https://github.com/openwrt/openwrt/commit/915a57ccd9086db88ee74cfa531ff13f8652a447#comments

**Comment by ttc0419** [comment]
@hauke Seems iwinfo still not installed by default, mind to take a look?

**Comment by hauke** [comment]
The `iwinfo` package is not installed any more by default and normally empty, see 30b35ff5ae7be41d772812c232083d5bbf3fabb0. `iwinfo` is provided by the `wifi-scripts`.
