### ISSUE TITLE
When running make package/install, the build failed with make -r world: build failed due to package conflicts that prevented package selection

### ISSUE THREAD

**Issue by teleostnacl** [openwrt/openwrt#21257]
### Describe the bug

After pulling the latest commit on the main branch, make package/install fails with make -r world: build failed due to package conflicts that prevent package selection.

Logs are shown below.
```text
make package/install V=sc
make[2]: Entering directory 'openwrt/scripts/config'
make[2]: 'conf' is up to date.
make[2]: Leaving directory 'openwrt/scripts/config'
make[1]: Entering directory 'openwrt'
rm -rf openwrt/staging_dir/packages/mediatek
mkdir -p openwrt/staging_dir/packages/mediatek
ln -s openwrt/bin/targets/mediatek/filogic/packages/*.apk openwrt/staging_dir/packages/mediatek; ln -s openwrt/bin/packages/aarch64_cortex-a53/base/*.apk openwrt/staging_dir/packages/mediatek; ln -s openwrt/bin/packages/aarch64_cortex-a53/luci/*.apk openwrt/staging_dir/packages/mediatek; ln -s openwrt/bin/packages/aarch64_cortex-a53/packages/*.apk openwrt/staging_dir/packages/mediatek;
(cd openwrt/staging_dir/packages/mediatek && openwrt/staging_dir/host/bin/apk mkndx \
                --root openwrt \
                --keys-dir openwrt \
                --allow-untrusted \
                --sign openwrt/private-key.pem \
                --output packages.adb \
                *.apk; \
)
Index has 344 packages (of which 344 are new)
find openwrt/staging_dir/target-aarch64_cortex-a53_musl/root-mediatek -type d | xargs -r chmod 0755
rm -rf openwrt/build_dir/target-aarch64_cortex-a53_musl/root-mediatek openwrt/build_dir/target-aarch64_cortex-a53_musl/root.orig-mediatek
mkdir -p openwrt/build_dir/target-aarch64_cortex-a53_musl/root-mediatek/tmp
IPKG_INSTROOT=openwrt/build_dir/target-aarch64_cortex-a53_musl/root-mediatek openwrt/staging_dir/host/bin/fakeroot openwrt/staging_dir/host/bin/apk --root openwrt/build_dir/target-aarch64_cortex-a53_musl/root-mediatek --keys-dir openwrt --no-logfile --preserve-env add --no-cache --initdb --no-scripts --arch aarch64_cortex-a53 \
        --repositories-file /dev/null --repository file://openwrt/staging_dir/packages/mediatek/packages.adb \
         \
        $(cat openwrt/tmp/apk_install_list) \
                "base-files=1677~74b5a63cf9" \
                "libc=1.2.5-r5" \
                "kernel=6.12.62~cdbbaf6403094fd68db5b0a1ec5c9fd8-r1"
ERROR: unable to select packages:
  ca-bundle-20250419-r1:
    conflicts: ca-certificates-20250419-r1[ca-certs=20250419-r1]
    satisfies: world[ca-bundle] libcurl4-8.15.0-r1[ca-bundle] xray-core-25.12.8-r1[ca-bundle]
  ca-certificates-20250419-r1:
    conflicts: ca-bundle-20250419-r1[ca-certs=20250419-r1]
    satisfies: world[ca-certificates] dockerd-27.3.1-r4[ca-certificates]
  v2ray-geoip-202510050144-r1:
    conflicts: v2ray-geosite-20250916122507-r1[v2ray-geodata=202510050144-r1]
               v2ray-geosite-20250916122507-r1[xray-geodata=202510050144-r1]
    satisfies: world[v2ray-geoip] luci-app-passwall2-25.12.18-r1[v2ray-geoip]
  v2ray-geosite-20250916122507-r1:
    conflicts: v2ray-geoip-202510050144-r1[v2ray-geodata=20250916122507-r1]
               v2ray-geoip-202510050144-r1[xray-geodata=20250916122507-r1]
    satisfies: world[v2ray-geosite] luci-app-passwall2-25.12.18-r1[v2ray-geosite]
make[1]: *** [package/Makefile:100: package/install] Error 12
make[1]: Leaving directory 'openwrt'
make: *** [openwrt/include/toplevel.mk:233: package/install] Error 2
```

### OpenWrt version

r32359-22a69dfa4a

### OpenWrt release

SNAPSHOT

### OpenWrt target/subtarget

mediatek/filogic

### Device

CMCC RAX3000M

### Image kind

Self-built image

### Diffconfig

```text
CONFIG_TARGET_mediatek=y
CONFIG_TARGET_mediatek_filogic=y
CONFIG_TARGET_mediatek_filogic_DEVICE_cmcc_rax3000m=y
CONFIG_BUSYBOX_CUSTOM=y
CONFIG_BIND_ENABLE_DOH=y
CONFIG_BUSYBOX_CONFIG_FEATURE_TELNET_AUTOLOGIN=y
CONFIG_BUSYBOX_CONFIG_FEATURE_TELNET_TTYPE=y
CONFIG_BUSYBOX_CONFIG_FEATURE_TELNET_WIDTH=y
CONFIG_BUSYBOX_CONFIG_TELNET=y
CONFIG_LIBCURL_COOKIES=y
CONFIG_LIBCURL_FILE=y
CONFIG_LIBCURL_FTP=y
CONFIG_LIBCURL_HTTP=y
CONFIG_LIBCURL_HTTP2=y
CONFIG_LIBCURL_NO_SMB="!"
CONFIG_LIBCURL_OPENSSL=y
CONFIG_LIBCURL_PROXY=y
CONFIG_LIBCURL_UNIX_SOCKETS=y
CONFIG_LIBSODIUM_MINIMAL=y
CONFIG_LUCI_LANG_zh_Hans=y
CONFIG_OPENSSL_ENGINE=y
CONFIG_OPENSSL_WITH_ASM=y
CONFIG_OPENSSL_WITH_CHACHA_POLY1305=y
CONFIG_OPENSSL_WITH_CMS=y
CONFIG_OPENSSL_WITH_DEPRECATED=y
CONFIG_OPENSSL_WITH_ERROR_MESSAGES=y
CONFIG_OPENSSL_WITH_IDEA=y
CONFIG_OPENSSL_WITH_MDC2=y
CONFIG_OPENSSL_WITH_PSK=y
CONFIG_OPENSSL_WITH_SEED=y
CONFIG_OPENSSL_WITH_SRP=y
CONFIG_OPENSSL_WITH_TLS13=y
CONFIG_OPENSSL_WITH_WHIRLPOOL=y
# CONFIG_PACKAGE_apk-mbedtls is not set
CONFIG_PACKAGE_apk-openssl=y
CONFIG_PACKAGE_attendedsysupgrade-common=y
CONFIG_PACKAGE_bind-dig=y
CONFIG_PACKAGE_bind-libs=y
CONFIG_PACKAGE_block-mount=y
CONFIG_PACKAGE_blockd=y
CONFIG_PACKAGE_btrfs-progs=y
CONFIG_PACKAGE_ca-certificates=y
CONFIG_PACKAGE_cgi-io=y
CONFIG_PACKAGE_chinadns-ng=y
CONFIG_PACKAGE_collectd=y
CONFIG_PACKAGE_collectd-mod-cpu=y
CONFIG_PACKAGE_collectd-mod-interface=y
CONFIG_PACKAGE_collectd-mod-iwinfo=y
CONFIG_PACKAGE_collectd-mod-load=y
CONFIG_PACKAGE_collectd-mod-memory=y
CONFIG_PACKAGE_collectd-mod-network=y
CONFIG_PACKAGE_collectd-mod-rrdtool=y
CONFIG_PACKAGE_containerd=y
CONFIG_PACKAGE_coreutils=y
CONFIG_PACKAGE_coreutils-base64=y
CONFIG_PACKAGE_coreutils-nohup=y
CONFIG_PACKAGE_curl=y
# CONFIG_PACKAGE_dnsmasq is not set
CONFIG_PACKAGE_dnsmasq-full=y
CONFIG_PACKAGE_dnsmasq_full_auth=y
CONFIG_PACKAGE_dnsmasq_full_conntrack=y
CONFIG_PACKAGE_dnsmasq_full_dhcp=y
CONFIG_PACKAGE_dnsmasq_full_dhcpv6=y
CONFIG_PACKAGE_dnsmasq_full_dnssec=y
CONFIG_PACKAGE_dnsmasq_full_nftset=y
CONFIG_PACKAGE_dnsmasq_full_noid=y
CONFIG_PACKAGE_docker=y
CONFIG_PACKAGE_docker-compose=y
CONFIG_PACKAGE_dockerd=y
CONFIG_PACKAGE_ethtool-full=y
CONFIG_PACKAGE_f2fs-tools=y
CONFIG_PACKAGE_geoview=y
CONFIG_PACKAGE_hping3=y
CONFIG_PACKAGE_httping=y
CONFIG_PACKAGE_ip-full=y
CONFIG_PACKAGE_ip6tables-nft=y
CONFIG_PACKAGE_iperf3=y
CONFIG_PACKAGE_iptables-mod-extra=y
CONFIG_PACKAGE_iptables-nft=y
CONFIG_PACKAGE_iwinfo=y
CONFIG_PACKAGE_kmod-br-netfilter=y
CONFIG_PACKAGE_kmod-crypto-acompress=y
CONFIG_PACKAGE_kmod-crypto-blake2b=y
CONFIG_PACKAGE_kmod-crypto-crc32=y
CONFIG_PACKAGE_kmod-crypto-xxhash=y
CONFIG_PACKAGE_kmod-fs-autofs4=y
CONFIG_PACKAGE_kmod-fs-btrfs=y
CONFIG_PACKAGE_kmod-fs-f2fs=y
# CONFIG_PACKAGE_kmod-gpio-button-hotplug is not set
CONFIG_PACKAGE_kmod-ip6tables=y
CONFIG_PACKAGE_kmod-ipt-conntrack=y
CONFIG_PACKAGE_kmod-ipt-core=y
CONFIG_PACKAGE_kmod-ipt-extra=y
CONFIG_PACKAGE_kmod-ipt-nat=y
CONFIG_PACKAGE_kmod-ipt-nat6=y
CONFIG_PACKAGE_kmod-ipt-physdev=y
# CONFIG_PACKAGE_kmod-leds-gpio is not set
CONFIG_PACKAGE_kmod-lib-crc-itu-t=y
CONFIG_PACKAGE_kmod-lib-lzo=y
CONFIG_PACKAGE_kmod-lib-raid6=y
CONFIG_PACKAGE_kmod-lib-xor=y
CONFIG_PACKAGE_kmod-lib-xxhash=y
CONFIG_PACKAGE_kmod-lib-zlib-deflate=y
CONFIG_PACKAGE_kmod-lib-zlib-inflate=y
CONFIG_PACKAGE_kmod-lib-zstd=y
CONFIG_PACKAGE_kmod-libphy=y
CONFIG_PACKAGE_kmod-loop=y
CONFIG_PACKAGE_kmod-mt76=y
CONFIG_PACKAGE_kmod-mt7603=y
CONFIG_PACKAGE_kmod-mt76x02-common=y
CONFIG_PACKAGE_kmod-mt76x2=y
CONFIG_PACKAGE_kmod-mt76x2-common=y
CONFIG_PACKAGE_kmod-mtd-rw=y
CONFIG_PACKAGE_kmod-nf-conntrack-netlink=y
CONFIG_PACKAGE_kmod-nf-ipt=y
CONFIG_PACKAGE_kmod-nf-ipt6=y
CONFIG_PACKAGE_kmod-nf-ipvs=y
CONFIG_PACKAGE_kmod-nf-nat6=y
CONFIG_PACKAGE_kmod-nf-socket=y
CONFIG_PACKAGE_kmod-nf-tproxy=y
CONFIG_PACKAGE_kmod-nft-compat=y
CONFIG_PACKAGE_kmod-nft-socket=y
CONFIG_PACKAGE_kmod-nft-tproxy=y
CONFIG_PACKAGE_kmod-nls-cp936=y
CONFIG_PACKAGE_kmod-nls-utf8=y
CONFIG_PACKAGE_kmod-phy-aquantia=y
CONFIG_PACKAGE_kmod-scsi-core=y
CONFIG_PACKAGE_kmod-usb-storage=y
CONFIG_PACKAGE_kmod-veth=y
CONFIG_PACKAGE_libatomic=y
CONFIG_PACKAGE_libattr=y
CONFIG_PACKAGE_libbpf=y
CONFIG_PACKAGE_libcap=y
CONFIG_PACKAGE_libcap-ng=y
CONFIG_PACKAGE_libcurl=y
CONFIG_PACKAGE_libdnet=y
CONFIG_PACKAGE_libelf=y
CONFIG_PACKAGE_libev=y
CONFIG_PACKAGE_libgmp=y
CONFIG_PACKAGE_libiperf3=y
CONFIG_PACKAGE_libiptext=y
CONFIG_PACKAGE_libiptext-nft=y
CONFIG_PACKAGE_libiptext6=y
CONFIG_PACKAGE_libiwinfo=y
CONFIG_PACKAGE_libiwinfo-data=y
CONFIG_PACKAGE_libltdl=y
CONFIG_PACKAGE_liblua=y
CONFIG_PACKAGE_liblucihttp=y
CONFIG_PACKAGE_liblucihttp-lua=y
CONFIG_PACKAGE_liblucihttp-ucode=y
CONFIG_PACKAGE_liblzo=y
# CONFIG_PACKAGE_libmbedtls is not set
CONFIG_PACKAGE_libmount=y
CONFIG_PACKAGE_libncurses=y
CONFIG_PACKAGE_libnetfilter-conntrack=y
CONFIG_PACKAGE_libnettle=y
CONFIG_PACKAGE_libnfnetlink=y
CONFIG_PACKAGE_libnghttp2=y
CONFIG_PACKAGE_libopenssl=y
CONFIG_PACKAGE_libopenssl-conf=y
CONFIG_PACKAGE_libopenssl-legacy=y
CONFIG_PACKAGE_libpcap=y
CONFIG_PACKAGE_libpcre2=y
CONFIG_PACKAGE_librrd1=y
CONFIG_PACKAGE_libseccomp=y
CONFIG_PACKAGE_libsodium=y
CONFIG_PACKAGE_libubus-lua=y
CONFIG_PACKAGE_libuci-lua=y
CONFIG_PACKAGE_libudns=y
CONFIG_PACKAGE_liburcu=y
# CONFIG_PACKAGE_libustream-mbedtls is not set
CONFIG_PACKAGE_libustream-openssl=y
CONFIG_PACKAGE_libuv=y
CONFIG_PACKAGE_libwebsockets-full=y
CONFIG_PACKAGE_libxtables=y
CONFIG_PACKAGE_lua=y
CONFIG_PACKAGE_luci=y
CONFIG_PACKAGE_luci-app-argon-config=y
CONFIG_PACKAGE_luci-app-attendedsysupgrade=y
CONFIG_PACKAGE_luci-app-dockerman=y
CONFIG_PACKAGE_luci-app-firewall=y
CONFIG_PACKAGE_luci-app-package-manager=y
CONFIG_PACKAGE_luci-app-passwall2=y
CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_ShadowsocksR_Libev_Client=y
CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_Simple_Obfs=y
CONFIG_PACKAGE_luci-app-passwall2_Nftables_Transparent_Proxy=y
CONFIG_PACKAGE_luci-app-statistics=y
CONFIG_PACKAGE_luci-app-ttyd=y
CONFIG_PACKAGE_luci-app-upnp=y
CONFIG_PACKAGE_luci-base=y
CONFIG_PACKAGE_luci-compat=y
CONFIG_PACKAGE_luci-i18n-argon-config-zh-cn=y
CONFIG_PACKAGE_luci-i18n-attendedsysupgrade-zh-cn=y
CONFIG_PACKAGE_luci-i18n-base-zh-cn=y
CONFIG_PACKAGE_luci-i18n-dockerman-zh-cn=y
CONFIG_PACKAGE_luci-i18n-firewall-zh-cn=y
CONFIG_PACKAGE_luci-i18n-package-manager-zh-cn=y
CONFIG_PACKAGE_luci-i18n-passwall2-zh-cn=y
CONFIG_PACKAGE_luci-i18n-statistics-zh-cn=y
CONFIG_PACKAGE_luci-i18n-ttyd-zh-cn=y
CONFIG_PACKAGE_luci-i18n-upnp-zh-cn=y
CONFIG_PACKAGE_luci-lib-base=y
CONFIG_PACKAGE_luci-lib-docker=y
CONFIG_PACKAGE_luci-lib-ip=y
CONFIG_PACKAGE_luci-lib-jsonc=y
CONFIG_PACKAGE_luci-lib-nixio=y
CONFIG_PACKAGE_luci-lib-uqr=y
CONFIG_PACKAGE_luci-light=y
CONFIG_PACKAGE_luci-lua-runtime=y
CONFIG_PACKAGE_luci-mod-admin-full=y
CONFIG_PACKAGE_luci-mod-network=y
CONFIG_PACKAGE_luci-mod-status=y
CONFIG_PACKAGE_luci-mod-system=y
CONFIG_PACKAGE_luci-proto-ipv6=y
CONFIG_PACKAGE_luci-proto-ppp=y
CONFIG_PACKAGE_luci-theme-argon=y
CONFIG_PACKAGE_luci-theme-bootstrap=y
CONFIG_PACKAGE_miniupnpd-nftables=y
CONFIG_PACKAGE_musl-fts=y
CONFIG_PACKAGE_resolveip=y
CONFIG_PACKAGE_rpcd=y
CONFIG_PACKAGE_rpcd-mod-file=y
CONFIG_PACKAGE_rpcd-mod-iwinfo=y
CONFIG_PACKAGE_rpcd-mod-luci=y
CONFIG_PACKAGE_rpcd-mod-rpcsys=y
CONFIG_PACKAGE_rpcd-mod-rrdns=y
CONFIG_PACKAGE_rpcd-mod-ucode=y
CONFIG_PACKAGE_rrdtool1=y
CONFIG_PACKAGE_runc=y
CONFIG_PACKAGE_shadowsocksr-libev-ssr-local=y
CONFIG_PACKAGE_shadowsocksr-libev-ssr-redir=y
CONFIG_PACKAGE_simple-obfs-client=y
CONFIG_PACKAGE_tcpbridge=y
CONFIG_PACKAGE_tcpcapinfo=y
CONFIG_PACKAGE_tcpdump=y
CONFIG_PACKAGE_tcping=y
CONFIG_PACKAGE_tcpliveplay=y
CONFIG_PACKAGE_tcpprep=y
CONFIG_PACKAGE_tcpreplay=y
CONFIG_PACKAGE_tcpreplay-all=y
CONFIG_PACKAGE_tcpreplay-edit=y
CONFIG_PACKAGE_tcprewrite=y
CONFIG_PACKAGE_terminfo=y
CONFIG_PACKAGE_tini=y
CONFIG_PACKAGE_ttyd=y
CONFIG_PACKAGE_ucode-mod-html=y
CONFIG_PACKAGE_ucode-mod-log=y
CONFIG_PACKAGE_ucode-mod-lua=y
CONFIG_PACKAGE_ucode-mod-math=y
CONFIG_PACKAGE_uhttpd=y
CONFIG_PACKAGE_uhttpd-mod-ubus=y
CONFIG_PACKAGE_unzip=y
CONFIG_PACKAGE_v2ray-geoip=y
CONFIG_PACKAGE_v2ray-geosite=y
CONFIG_PACKAGE_vim=y
CONFIG_PACKAGE_wget-ssl=y
# CONFIG_PACKAGE_wpad-basic-mbedtls is not set
CONFIG_PACKAGE_wpad-openssl=y
CONFIG_PACKAGE_xray-core=y
CONFIG_PACKAGE_xtables-nft=y
# CONFIG_WIFI_SCRIPTS_UCODE is not set
# CONFIG_PACKAGE_dnsmasq_full_tftp is not set
# CONFIG_PACKAGE_haproxy is not set
# CONFIG_PACKAGE_kmod-inet-diag is not set
# CONFIG_PACKAGE_kmod-tun is not set
# CONFIG_PACKAGE_liblua5.4 is not set
# CONFIG_PACKAGE_libmbedtls is not set
# CONFIG_PACKAGE_libreadline is not set
# CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_Haproxy is not set
# CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_Shadowsocks_Libev_Client is not set
# CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_Shadowsocks_Rust_Client is not set
# CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_SingBox is not set
# CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_V2ray_Plugin is not set
# CONFIG_PACKAGE_shadowsocks-libev-ss-local is not set
# CONFIG_PACKAGE_shadowsocks-libev-ss-redir is not set
# CONFIG_PACKAGE_shadowsocks-rust-sslocal is not set
# CONFIG_PACKAGE_sing-box is not set
# CONFIG_PACKAGE_v2ray-plugin is not set
# CONFIG_PCRE2_JIT_ENABLED is not set
```

### Terms

- [x] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by teleostnacl** [comment]
[openwrt-passwall-packages](https://github.com/xiaorouji/openwrt-passwall-packages)
[openwrt-passwall2](https://github.com/xiaorouji/openwrt-passwall2)

**Comment by brada4** [comment]
Those repos are not related to official OpenWrt.  You have to seek help somewhere else.

**Comment by linexu** [comment]
**Pure official firmware, no third-party plug-ins. Same error.**

```echo "mkf2fs" >> /home/xu/op/staging_dir/target-x86_64_musl/pkginfo/f2fs-tools.default.install
make[3]: Leaving directory '/home/xu/op/package/utils/f2fs-tools'
time: package/utils/f2fs-tools/default/compile#2.09#0.70#2.51
make[2]: Leaving directory '/home/xu/op'
make[2]: Entering directory '/home/xu/op'
rm -rf /home/xu/op/staging_dir/packages/x86
mkdir -p /home/xu/op/staging_dir/packages/x86
ln -s /home/xu/op/bin/targets/x86/64/packages/*.apk /home/xu/op/staging_dir/packages/x86; ln -s /home/xu/op/bin/packages/x86_64/base/*.apk /home/xu/op/staging_dir/packages/x86; ln -s /home/xu/op/bin/packages/x86_64/luci/*.apk /home/xu/op/staging_dir/packages/x86; ln -s /home/xu/op/bin/packages/x86_64/packages/*.apk /home/xu/op/staging_dir/packages/x86;   
(cd /home/xu/op/staging_dir/packages/x86 && /home/xu/op/staging_dir/host/bin/apk mkndx \
                --root /home/xu/op \
                --keys-dir /home/xu/op \
                --allow-untrusted \
                --sign /home/xu/op/private-key.pem \
                --output packages.adb \
                *.apk; \
)
Index has 318 packages (of which 318 are new)
find /home/xu/op/staging_dir/target-x86_64_musl/root-x86 -type d | xargs -r chmod 0755
rm -rf /home/xu/op/build_dir/target-x86_64_musl/root-x86 /home/xu/op/build_dir/target-x86_64_musl/root.orig-x86
mkdir -p /home/xu/op/build_dir/target-x86_64_musl/root-x86/tmp
IPKG_INSTROOT=/home/xu/op/build_dir/target-x86_64_musl/root-x86 /home/xu/op/staging_dir/host/bin/fakeroot /home/xu/op/staging_dir/host/bin/apk --root /home/xu/op/build_dir/target-x86_64_musl/root-x86 --keys-dir /home/xu/op --no-logfile --preserve-env add --no-cache --initdb --no-scripts --arch x86_64 \
        --repositories-file /dev/null --repository file:///home/xu/op/staging_dir/packages/x86/packages.adb \
         \
        $(cat /home/xu/op/tmp/apk_install_list) \
                "base-files=1677~b43f7bc9c2" \
                "libc=1.2.5-r5" \
                "kernel=6.12.62~1e7cac40d650707554225729aa7350c6-r1"
ERROR: unable to select packages:
  v2ray-geoip-202510050144-r1:
    conflicts: v2ray-geosite-20250916122507-r1[v2ray-geodata=202510050144-r1]
               v2ray-geosite-20250916122507-r1[xray-geodata=202510050144-r1]
    satisfies: world[v2ray-geoip]
  v2ray-geosite-20250916122507-r1:
    conflicts: v2ray-geoip-202510050144-r1[v2ray-geodata=20250916122507-r1]
               v2ray-geoip-202510050144-r1[xray-geodata=20250916122507-r1]
    satisfies: world[v2ray-geosite]
make[2]: *** [package/Makefile:100: package/install] Error 2
make[2]: Leaving directory '/home/xu/op'
make[1]: *** [package/Makefile:182: /home/xu/op/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/xu/op'
make: *** [/home/xu/op/include/toplevel.mk:233：world] Error 2

**Comment by teleostnacl** [comment]
Hi @brada4, thanks for your reply.

However, ook this message:
```text
  ca-bundle-20250419-r1:
    conflicts: ca-certificates-20250419-r1[ca-certs=20250419-r1]
    satisfies: world[ca-bundle] libcurl4-8.15.0-r1[ca-bundle] xray-core-25.12.8-r1[ca-bundle]
  ca-certificates-20250419-r1:
    conflicts: ca-bundle-20250419-r1[ca-certs=20250419-r1]
    satisfies: world[ca-certificates] dockerd-27.3.1-r4[ca-certificates]
```

`libcurl4-8.15.0-r1` requires `ca-bundle`, whereas `dockerd-27.3.1-r4` requires `ca-certificates`. Since both packages provide `ca-certs`, they conflict with each other.

And these are all official packages.

It looks like a recent change triggered this issue.

**Comment by linexu** [comment]
> Those repos are not related to official OpenWrt. You have to seek help somewhere else.

Do you have any evidence to support your statement? Don't jump to conclusions casually, that's nonsense.

**Comment by linexu** [comment]
**Cancel v2ray-geoip & v2ray-geosite.**

```Generating package index...
Index has 107 packages (of which 107 are new)
Index has 100 packages (of which 100 are new)
Index has 59 packages (of which 59 are new)
Index has 52 packages (of which 52 are new)
make[2]: Leaving directory '/home/xu/op'
export MAKEFLAGS= ;make -w -r json_overview_image_info
make[2]: Entering directory '/home/xu/op'
WORK_DIR=/home/xu/op/build_dir/target-x86_64_musl/json_info_files /home/xu/op/scripts/json_overview_image_info.py /home/xu/op/bin/targets/x86/64/profiles.json 
make[2]: Leaving directory '/home/xu/op'
export MAKEFLAGS= ;make -w -r checksum
make[2]: Entering directory '/home/xu/op'
make[2]: Leaving directory '/home/xu/op'
make[1]: Leaving directory '/home/xu/op'

**Comment by GeorgeSapkin** [comment]
This is indeed caused by the recent APK changes. I see ca-certificates is somewhat special as it should be possible to install it side-by-side with ca-bundle.

**Comment by linexu** [comment]
```Index has 385 packages (of which 385 are new)
find /home/xu/op/staging_dir/target-x86_64_musl/root-x86 -type d | xargs -r chmod 0755
rm -rf /home/xu/op/build_dir/target-x86_64_musl/root-x86 /home/xu/op/build_dir/target-x86_64_musl/root.orig-x86
mkdir -p /home/xu/op/build_dir/target-x86_64_musl/root-x86/tmp
IPKG_INSTROOT=/home/xu/op/build_dir/target-x86_64_musl/root-x86 /home/xu/op/staging_dir/host/bin/fakeroot /home/xu/op/staging_dir/host/bin/apk --root /home/xu/op/build_dir/target-x86_64_musl/root-x86 --keys-dir /home/xu/op --no-logfile --preserve-env add --no-cache --initdb --no-scripts --arch x86_64 \
        --repositories-file /dev/null --repository file:///home/xu/op/staging_dir/packages/x86/packages.adb \
         \
        $(cat /home/xu/op/tmp/apk_install_list) \
                "base-files=1677~b43f7bc9c2" \
                "libc=1.2.5-r5" \
                "kernel=6.12.62~075c576a2dd909faf511dfc65f93df73-r1"
ERROR: unable to select packages:
  ca-bundle-20250419-r1:
    conflicts: ca-certificates-20250419-r1[ca-certs=20250419-r1]
    satisfies: world[ca-bundle] acme-acmesh-3.1.1-r4[ca-bundle] adblock-4.4.5-r2[ca-bundle] cloudflared-2025.11.0-r2[ca-bundle]
               dnsproxy-0.78.2-r1[ca-bundle] hysteria-2.6.5-r1[ca-bundle] libcurl4-8.15.0-r1[ca-bundle]
               luci-app-xray-3.6.1-r1[ca-bundle] mosdns-5.3.3-r1[ca-bundle] sing-box-1.12.12-r1[ca-bundle]
               tailscale-1.92.3-r1[ca-bundle] v2ray-core-5.41.0-r1[ca-bundle] v2ray-plugin-5.41.0-r1[ca-bundle]
               v2raya-2.2.7.4-r1[ca-bundle] xray-core-25.12.8-r1[ca-bundle]
  ca-certificates-20250419-r1:
    conflicts: ca-bundle-20250419-r1[ca-certs=20250419-r1]
    satisfies: world[ca-certificates] speedtest-cli-1.2.0-r1[ca-certificates]
  jq-1.8.1-r1:
    conflicts: jq-1.8.1-r1[jq=1.8.1-r1]
    satisfies: world[jq] luci-app-ssr-plus-190-r3[jq]
make[2]: *** [package/Makefile:100: package/install] Error 37
make[2]: Leaving directory '/home/xu/op'
make[1]: *** [package/Makefile:182: /home/xu/op/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/xu/op'
make: *** [/home/xu/op/include/toplevel.mk:233：world] Error 2

**Comment by namiltd** [comment]
Paste the logs between:
\`\`\`

\`\`\`
because otherwise they look weird

**Comment by brada4** [comment]
You have package conflicting self, meaning 3rd party repo duplicates OpenWrt package.

**Comment by linexu** [comment]
> You have package conflicting self, meaning 3rd party repo duplicates OpenWrt package.

You are so smart, how do you explain the same failure message when there is no third-party package?

**Comment by robimarko** [comment]
@GeorgeSapkin I am wondering how this even worked before since there are 2 packages with the same PROVIDES.

**Comment by linexu** [comment]
> [@GeorgeSapkin](https://github.com/GeorgeSapkin) I am wondering how this even worked before since there are 2 packages with the same PROVIDES.

I'm guessing there has been no judgment on this before.

**Comment by robimarko** [comment]
@GeorgeSapkin @efahl Would adding a variant definition to ca-bundle and ca-certificates work?

For me it seems to allow installing both at the same time

**Comment by GeorgeSapkin** [comment]
@robimarko without looking at either the old or the new code, I assume old provides weren't versioned and acted as a virtual package, that can be required but won't be installed automatically. Non-versioned provides don't own the name, and can be installed side by side. 

I'm not sure how variant functions. There are multiple ways this issue can be addressed. Like making certificates a _full_ version of the bundle that includes both individual certs and a bundle. Or introducing a new field that would allow to define a non-versioned virtual package. Provides are kind of used in a manner that doesn't really fit with APK I think. As there is a lot of magic on top of package definition. Ideally each package should decide what exactly it provides and not have to worry about implicit behavior.

I won't be able to actually look into this until tomorrow afternoon at the earliest. 

Edit: are maybe having some prefix to mark provides as virtual, like \@VIRTUAL:ca-certs.

**Comment by efahl** [comment]
I've been combing through Alpine packages trying to find something similar, but nothing yet.

Closest approximation in OpenWrt is the `wget` situation: all of `uclient-fetch`, `wget-nossl` and `wget-ssl` provide `wget`, and you can have `uclient-fetch` and one `wget-*` variant installed simultaneously...  (But, I haven't tried building this with the recent commits, so maybe it's broken, too???)

From my snapshot test machine:
```bash
$ apk query --fields package,name,provides,contents uclient-fetch wget-ssl
Package: uclient-fetch-2025.10.03~dc909ca7-r1
Name: uclient-fetch
Provides: wget
Contents:
  bin/uclient-fetch
  lib/apk/packages/uclient-fetch.alternatives
  lib/apk/packages/uclient-fetch.list

Package: wget-ssl-1.25.0-r1
Name: wget-ssl
Provides: gnu-wget wget
Contents:
  lib/apk/packages/wget-ssl.alternatives
  lib/apk/packages/wget-ssl.list
  usr/libexec/wget-ssl
```

**Comment by linexu** [comment]
I would like to ask if this kind of thing happened, is OPENWRT deliberately tormenting everyone?
If I'm wrong, please ignore it.

**Comment by smallprogram** [comment]
According to the official feeds, some packages depend on `ca-bundle-20250419-r1`, while others depend on `ca-certificates-20250419-r1`.
However, `ca-bundle-20250419-r1` and `ca-certificates-20250419-r1` cannot be installed together in the latest source code, which is causing this problem.
The root cause of the problem stems from @GeorgeSapkin's modification to the `include/package-pack.mk` file yesterday.

Specific submission details：https://github.com/openwrt/openwrt/compare/2da39423ed90372cf9679ea11a5e9c3240bc2e47...eaeae068cccf549acf2c296e7e1ad0e331def102

**Comment by schuettecarsten** [comment]
> The root cause of the problem stems from @GeorgeSapkin's modification to the `include/package-pack.mk` file yesterday.

> Specific submission details：https://github.com/openwrt/openwrt/compare/2da39423ed90372cf9679ea11a5e9c3240bc2e47...eaeae068cccf549acf2c296e7e1ad0e331def102

@robimarko @GeorgeSapkin
Can you please think about reverting the changes until packages are fixed?

**Comment by robimarko** [comment]
I would honestly rather fix this instead of reverting.
25.12 RC1 does not have this issue

**Comment by larena1** [comment]
```
ERROR: unable to select packages:
  pbr-1.2.1-r41:                                                         
conflicts: pbr-1.2.1-r41[pbr=1.2.1-r41]                              
satisfies: world[pbr] luci-app-pbr-1.2.0-r2[pbr]
```

This might be related. Never seen until now

**Comment by GeorgeSapkin** [comment]
I got a prototype working that addresses the ca-certs issue:

```bash
root@OpenWrt:/tmp# apk add --allow-untrusted ./ca-certificates-20250419-r2.apk ./ca-bundle-20250419-r2.apk
 
(1/2) Upgrading ca-bundle (20250419-r1 -> 20250419-r2)
  Executing ca-bundle-20250419-r2.post-upgrade
(2/2) Installing ca-certificates (20250419-r2)
  Executing ca-certificates-20250419-r2.post-install
OK: 18.3 MiB in 145 packages
```

There's no PR and no ETA, as this needs to be tested with more scenarios first, e.g. packages that depends on _virtual_ packages, packages with ABI, packages with ABI and provides, etc. I'll tag this issue, once I'm reasonably certain this is a working solution.

**Comment by GeorgeSapkin** [comment]
> ```
> ERROR: unable to select packages:
>   pbr-1.2.1-r41:                                                         
> conflicts: pbr-1.2.1-r41[pbr=1.2.1-r41]                              
> satisfies: world[pbr] luci-app-pbr-1.2.0-r2[pbr]
> ```
> 
> This might be related. Never seen until now

I don't think it's feasible for me to fix and test every non-core package with misconfigured dependency/provides issues. I can assist the maintainers or other contributors willing to step-up if they ping me.

**Comment by efahl** [comment]
> The root cause of the problem stems from...

No, the root cause is incorrect packaging spread across 10s or 100s of Makefiles, @GeorgeSapkin's fixes simply exposed those issues.  Snapshot is where these things get fixed, so snapshots break.  If you need stability, you should be on a stable release.

**Comment by lengfwong** [comment]
I have a similar error on branch 25.12, compiling passed after checkout commit 2da3942（revert 116083d eaeae06 e0ea3d7）.

**Comment by smallprogram** [comment]
> > The root cause of the problem stems from...
> 
> No, the root cause is incorrect packaging spread across 10s or 100s of Makefiles, [@GeorgeSapkin](https://github.com/GeorgeSapkin)'s fixes simply exposed those issues. Snapshot is where these things get fixed, so snapshots break. If you need stability, you should be on a stable release.

Your response is like Windows providing an update that causes many software programs to stop working, and then the Windows developers tell the developers of those affected programs to fix the problem themselves.

**Comment by robimarko** [comment]
> > No, the root cause is incorrect packaging spread across 10s or 100s of Makefiles, [@GeorgeSapkin](https://github.com/GeorgeSapkin)'s fixes simply exposed those issues. Snapshot is where these things get fixed, so snapshots break. If you need stability, you should be on a stable release.
> 
> Your response is like Windows providing an update that causes many software programs to stop working, and then the Windows developers tell the developers of those affected programs to fix the problem themselves.

He is correct though, nobody can test nor fix hundreds of weird packaging configs that were never even supposed to work.
Like any other change, this will take time to sort out and that is just life

**Comment by efahl** [comment]
> Your response is like Windows providing an update that causes many software programs to stop working, and then the Windows developers tell the developers of those affected programs to fix the problem themselves.

Yes, exactly.  But we have the luxury of not having to support broken legacy code.  Since it's open source, you can fix it, if it's important enough to you.

EDIT - I missed making the important point that _we don't have to carry that legacy cruft forever_ because we can (and do!) fix it, albeit at the cost of occasional build breakage...

**Comment by GeorgeSapkin** [comment]
The PR addressing ca-certs issue:
- https://github.com/openwrt/openwrt/pull/21288

**Comment by kvic-z** [comment]
I believe this is another data point: 

CONFIG_PACKAGE_jq=y

At the stage of make package/install:
````
ERROR: unable to select packages:
  jq-1.8.1-r1:
    conflicts: jq-1.8.1-r1[jq=1.8.1-r1]
    satisfies: world[jq]
````

No error before the changes introduced in [2da3942...eaeae06](https://github.com/openwrt/openwrt/compare/2da39423ed90372cf9679ea11a5e9c3240bc2e47...eaeae068cccf549acf2c296e7e1ad0e331def102)

**Comment by efahl** [comment]
Now this jq one is odd, as everything looks correct.  What is `apk` up to here?
```
$ apk query --fields package,name,version,provides,provider-priority jq\*
Package: jq-1.8.1-r1
Name: jq
Version: 1.8.1-r1
Provider-Priority: 100
Provides: jq=1.8.1-r1

Package: jq-full-1.8.1-r1
Name: jq-full
Version: 1.8.1-r1
Provider-Priority: 1
Provides: jq=1.8.1-r1

$ apk add jq
ERROR: unable to select packages:
  jq-1.8.1-r1:
    conflicts: jq-1.8.1-r1[jq=1.8.1-r1]
    satisfies: world[jq]
```

Seems all correct according to https://gitlab.alpinelinux.org/alpine/apk-tools/-/blob/master/doc/apk-package.5.scd?ref_type=heads#L195

**Comment by larena1** [comment]
It's probably that a package can't provide itself.

**Comment by GeorgeSapkin** [comment]
> It's probably that a package can't provide itself.

Correct. That makes no sense.

**Comment by efahl** [comment]
I think you're right.  This bit seems to imply that for the primary package there _not_ be a `provides=name` the same as the package itself.

       List of package names (and optionally its version) this package
	provides in addition to its primary name and version. The provided
	name can contain additionally characters: comma (,), brackets ([]),
	colons (:) and slashes (/) in the name.	This allows using namespaces
	for automatically generated names.

EDIT That "in addition to" part is what's making me think this...

**Comment by efahl** [comment]
Now I'm seeing implicit package replacements, too.  Imagebuilder uses `kmod-r8127` in place of the actually-installed `kmod-r8169`.
```
$ apk query --fields package,provides,provider-priority kmod-r81*
Package: kmod-r8101-6.12.62.1.039.00-r3
Provider-Priority: 1
Provides: kmod-r8169=6.12.62.1.039.00-r3
... a bunch of others ...
Package: kmod-r8127-6.12.62.11.015.00-r1
Provider-Priority: 1
Provides: kmod-r8169=6.12.62.11.015.00-r1

Package: kmod-r8168-rss-6.12.62.8.055.00-r4
Provider-Priority: 1
Provides: kmod-r8169=6.12.62.8.055.00-r4

Package: kmod-r8169-6.12.62-r1

```
And looking at https://gitlab.alpinelinux.org/alpine/apk-tools/-/blob/master/src/solver.c?ref_type=heads#L376 I'm wondering if those "providers" should have that priority set.  Or maybe we need to add explicit priority to the r8169 package?  (Highest wins: https://gitlab.alpinelinux.org/alpine/apk-tools/-/blob/master/src/solver.c?ref_type=heads#L662)

**Comment by GeorgeSapkin** [comment]
> Imagebuilder uses `kmod-r8127` in place of the actually-installed `kmod-r8169`.

@efahl I'm not familiar with these kmods to understand the issue. More details? Are they not supposed to provide something?

**Comment by efahl** [comment]
I think I've found it.  The default variant in https://github.com/openwrt/openwrt/blob/main/package/kernel/linux/modules/netdevices.mk#L1201 is not defined as the default variant, hence it does not get a priority (which would be 100 per package-pack logic):

```
DEFAULT_VARIANT:=1
```

**Comment by GeorgeSapkin** [comment]
OK, I got the issue. There's both an actual kmod with that name and others that provide it. And the actual one is not prioritized.

**Comment by GeorgeSapkin** [comment]
It's kind of strange why provider-priority would be set at all for non-default variants that have provides as per the docs.

I assume you're going to open a PR for kmods.

**Comment by map-b** [comment]
We did it dea839773c27430031c2a59c3d37ebdfef3937b9 , maybe it is time to think in revert that and take into account the alternative prioritites? The latter plus the actual DEFAULT_VARIANT logic to define provider-priority should cover all/most cases?? All the cases where the provides are shared and the provider-priority is required("virtual" in apk context, those which use ALTERNATIVES in openwrt context)[^1] should be covered.

[^1]: https://gitlab.alpinelinux.org/alpine/apk-tools/-/blob/master/doc/apk-package.5.scd?#L215

**Comment by map-b** [comment]
> I think I've found it. The default variant in https://github.com/openwrt/openwrt/blob/main/package/kernel/linux/modules/netdevices.mk#L1201 is not defined as the default variant, hence it does not get a priority (which would be 100 per package-pack logic):
> 
> ```
> DEFAULT_VARIANT:=1
> ```

Oh, the kmod-8169 is a special one it is provided by five different packages https://github.com/search?q=repo%3Aopenwrt%2Fopenwrt%20PROVIDES%3A%3Dkmod-r8169&type=code using the DEFAULT_VARIANT for defining provides-priority works in the context of only one package makefile defining all variants and providers. Maybe we need to introduce a new DEFAULT_PROVIDER variable for such cases?

**Comment by efahl** [comment]
Well, after fiddling with priority=100 on the base `kmod-r8169`, `apk` is still replacing it with the 8127 version.  

I dumped all of the variants, and it's pretty wacky.  The version numbers for all the packages are different, so there's something else going on here...

```
$ ~/openwrt/openwrt/staging_dir/host/bin/apk adbdump kmod-r8* | grep -E '^  (name:|version:|provid|  - kmod-r8)'
  name: kmod-r8101
  version: 6.12.62.1.039.00-r3
  provider-priority: 1
  provides: # 1 items
    - kmod-r8169=6.12.62.1.039.00-r3

  name: kmod-r8125
  version: 6.12.62.9.016.01-r1
  provider-priority: 1
  provides: # 1 items
    - kmod-r8169=6.12.62.9.016.01-r1

  name: kmod-r8125-rss
  version: 6.12.62.9.016.01-r1
  provider-priority: 1
  provides: # 1 items
    - kmod-r8169=6.12.62.9.016.01-r1

  name: kmod-r8126
  version: 6.12.62.10.016.00-r1
  provider-priority: 1
  provides: # 1 items
    - kmod-r8169=6.12.62.10.016.00-r1

  name: kmod-r8126-rss
  version: 6.12.62.10.016.00-r1
  provider-priority: 1
  provides: # 1 items
    - kmod-r8169=6.12.62.10.016.00-r1

  name: kmod-r8127
  version: 6.12.62.11.015.00-r1
  provider-priority: 1
  provides: # 1 items
    - kmod-r8169=6.12.62.11.015.00-r1

  name: kmod-r8127-rss
  version: 6.12.62.11.015.00-r1
  provider-priority: 1
  provides: # 1 items
    - kmod-r8169=6.12.62.11.015.00-r1

  name: kmod-r8168
  version: 6.12.62.8.055.00-r4
  provider-priority: 1
  provides: # 1 items
    - kmod-r8169=6.12.62.8.055.00-r4

  name: kmod-r8168-rss
  version: 6.12.62.8.055.00-r4
  provider-priority: 1
  provides: # 1 items
    - kmod-r8169=6.12.62.8.055.00-r4

  name: kmod-r8169
  version: 6.12.62-r1
  provider-priority: 100

```

**Comment by linexu** [comment]
@GeorgeSapkin 
```WARNING: Makefile 'package/feeds/telephony/asterisk/Makefile' has a dependency on 'uw-imap', which does not exist
WARNING: Makefile 'package/feeds/packages/nmap/Makefile' has a dependency on 'ca-certs', which does not exist
WARNING: Makefile 'package/feeds/packages/nmap/Makefile' has a dependency on 'ca-certs', which does not exist
WARNING: Makefile 'package/feeds/packages/nmap/Makefile' has a dependency on 'ca-certs', which does not exist
WARNING: Makefile 'package/feeds/packages/nmap/Makefile' has a dependency on 'ca-certs', which does not exist
WARNING: Makefile 'package/feeds/packages/nmap/Makefile' has a dependency on 'ca-certs', which does not exist
WARNING: Makefile 'package/feeds/packages/onionshare-cli/Makefile' has a dependency on 'python3-pysocks', which does not exist
WARNING: Makefile 'package/feeds/packages/onionshare-cli/Makefile' has a dependency on 'python3-unidecode', which does not exist
WARNING: Makefile 'package/feeds/packages/python3/Makefile' has a dependency on 'ca-certs', which does not exist
WARNING: Makefile 'package/feeds/packages/stubby/Makefile' has a dependency on 'ca-certs', which does not exist

**Comment by linexu** [comment]
@GeorgeSapkin 
I know, I followed your method and modified ```PROVIDES:=@ca-certs``` before the above warning appeared.
The compilation still fails.

```/home/xu/op/staging_dir/host/bin/fakeroot /home/xu/op/staging_dir/host/bin/apk mkpkg --info "name:ca-bundle" --info "version:20250419-r1"  --info "description:System CA certificates as a bundle" --info "arch:noarch" --info "license:GPL-2.0-or-later MPL-2.0" --info "origin:feeds/base/system/ca-certificates" --info "url:" --info "maintainer:" --info "provides:   @ca-certs=20250419-r1  " --info "provider-priority:1" --script "post-install:/home/xu/op/build_dir/target-x86_64_musl/ca-certificates-20250419/apk-all/ca-bundle/post-install" --script "post-upgrade:/home/xu/op/build_dir/target-x86_64_musl/ca-certificates-20250419/apk-all/ca-bundle/post-upgrade" --script "pre-deinstall:/home/xu/op/build_dir/target-x86_64_musl/ca-certificates-20250419/apk-all/ca-bundle/pre-deinstall" --info "depends:libc" --files "/home/xu/op/build_dir/target-x86_64_musl/ca-certificates-20250419/ipkg-all/ca-bundle" --output "/home/xu/op/bin/packages/x86_64/base/ca-bundle-20250419-r1.apk"
ERROR: info field 'provides' has invalid value: dependency format is invalid
ERROR: failed to create package: dependency format is invalid
make[3]: *** [Makefile:99: /home/xu/op/bin/packages/x86_64/base/ca-bundle-20250419-r1.apk] Error 99
make[3]: Leaving directory '/home/xu/op/package/system/ca-certificates'
time: package/system/ca-certificates/compile#1.12#0.29#1.37
    ERROR: package/system/ca-certificates failed to build.
make[2]: *** [package/Makefile:187: package/system/ca-certificates/compile] Error 1
make[2]: Leaving directory '/home/xu/op'
make[1]: *** [package/Makefile:181: /home/xu/op/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/xu/op'
make: *** [/home/xu/op/include/toplevel.mk:233：world] Error 2

**Comment by GeorgeSapkin** [comment]
> I followed your method and modified `PROVIDES:=@ca-certs` before the above warning appeared.

You need to apply the patch from #21288

**Comment by e9hack** [comment]
> I believe this is another data point:
> 
> CONFIG_PACKAGE_jq=y
> 
> At the stage of make package/install:
> 
> ```
> ERROR: unable to select packages:
>   jq-1.8.1-r1:
>     conflicts: jq-1.8.1-r1[jq=1.8.1-r1]
>     satisfies: world[jq]
> ```
> 
> No error before the changes introduced in [2da3942...eaeae06](https://github.com/openwrt/openwrt/compare/2da39423ed90372cf9679ea11a5e9c3240bc2e47...eaeae068cccf549acf2c296e7e1ad0e331def102)

It looks like that the definition `PROVIDES:=...` must not have the same value like the selected build package. If I modify the Makefile that the build package get the name jq-tiny instead of jq, the issue is gone. The same occurs, if I change `PROVIDES:=jq` to `PROVIDES:=jq-tool`. 

The same occurs with other packages. If I change `PROVIDES:=gnu-wget wget` to `PROVIDES:=wget-ssl`, a similar error occurs for wget-ssl.

**Comment by map-b** [comment]
~kmods~

**Comment by GeorgeSapkin** [comment]
@map-b the package name will be kmod-r8169, check KernelPackage in kernel.mk.

**Comment by efahl** [comment]
Blah, yet another variant.  tldr: packages depend on sanitized "alternate-name" for an ABI-versioned package.

The `readline` package depends on `libncursesw` (note the `w` suffix which is defined via provides, not the base name of the package).  https://github.com/openwrt/openwrt/blob/main/package/libs/readline/Makefile#L34  (Also, `fdisk` and `gawk` and maybe others do this.)

The `ncurses` package defines `PROVIDES:=libncursesw` https://github.com/openwrt/openwrt/blob/main/package/libs/ncurses/Makefile#L42, but _also an ABI version_.  So the package ends up with this:
```
$ apk adbdump ./bin/packages/x86_64/base/libncurses6-6.4-r3.apk
#%SCHEMA: 676B6370
# ADB block, size: 2456, compat: 0, ver: 0
info:
  name: libncurses6
  version: 6.4-r3
...
  provides: # 2 items
    - libncurses
    - libncursesw6=6.4-r3
  tags: # 1 items
    - openwrt:abiversion=6
```
And then when we build:
```
ERROR: unable to select packages:
  libncursesw (no such package):
    required by: libreadline8-8.3-r1[libncursesw]
                 fdisk-2.41.2-r1[libncursesw]
                 gawk-5.3.2-r1[libncursesw]
make[2]: *** [package/Makefile:100: package/install] Error 7
make[2]: Leaving directory '/home/efahlgren/openwrt/openwrt'
make[1]: *** [package/Makefile:182: /home/efahlgren/openwrt/openwrt/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/efahlgren/openwrt/openwrt'
make: *** [/home/efahlgren/openwrt/openwrt/include/toplevel.mk:233: world] Error 2
```

From previous builds we got (seems like this one is "most correct"):

`Provides: libncurses=6.4-r3 libncursesw libncursesw6=6.4-r3`

And in opkg it's:

`Provides: libncursesw, libncurses, libncursesw6`

**Comment by linexu** [comment]
> > I followed your method and modified `PROVIDES:=@ca-certs` before the above warning appeared.
> 
> You need to apply the patch from [#21288](https://github.com/openwrt/openwrt/pull/21288)

@GeorgeSapkin Hello, I used a translator and read all the content of [#21288] in great detail, but I couldn’t understand it at all. First of all, the translation is not very accurate. Secondly, the content you discussed is too professional. I don't know how to program, I just want to compile an openwrt firmware for my own use.
So how can I solve this error I encountered and make it compile successfully? Can you simply teach me how to operate it step by step, the more detailed the better? Thanks

**Comment by efahl** [comment]
> So how can I solve this error I encountered and make it compile successfully?

The easiest way is to simply wait for the fixes to be merged.

If you are testing these changes, you can apply the patches locally with something like
```
$ wget https://patch-diff.githubusercontent.com/raw/openwrt/openwrt/pull/21288.patch
$ git apply 21288.patch
$ make ...
```

**Comment by linexu** [comment]
> The easiest way is to simply wait for the fixes to be merged.
> 
> If you are testing these changes, you can apply the patches locally with something like

Thank you, I'll wait.

**Comment by GeorgeSapkin** [comment]
@efahl I don't quite get the ncurses/readline issue. I looked at the packaging and nothing jumps out:

```bash
root@OpenWrt:/tmp# apk add --allow-untrusted ./libncurses6-6.4-r3.apk ./libreadline8-8.3-r1.apk 
(1/3) Installing terminfo (6.4-r3)
  Executing terminfo-6.4-r3.post-install
(2/3) Installing libncurses6 (6.4-r3)
  Executing libncurses6-6.4-r3.post-install
(3/3) Installing libreadline8 (8.3-r1)
  Executing libreadline8-8.3-r1.post-install
OK: 22.8 MiB in 167 packages

root@OpenWrt:/tmp# apk query --fields name,version,depends,provides libncurses6 libreadline8
Name: libncurses6
Version: 6.4-r3
Depends: libc terminfo
Provides: libncurses libncursesw6=6.4-r3

Name: libreadline8
Version: 8.3-r1
Depends: libc libncursesw6
Provides: libreadline

```

This is built with my latest patcheset. What am I missing here?

**Comment by kvic-z** [comment]
> It looks like that the definition `PROVIDES:=...` must not have the same value like the selected build package. If I modify the Makefile that the build package get the name jq-tiny instead of jq, the issue is gone. The same occurs, if I change `PROVIDES:=jq` to `PROVIDES:=jq-tool`.
> 
> The same occurs with other packages. If I change `PROVIDES:=gnu-wget wget` to `PROVIDES:=wget-ssl`, a similar error occurs for wget-ssl.

I think OpenWrt dev's already had the solution for this particular scenario exposed by package jq. If I understand correctly "PROVIDES:=jq" is not needed. I checked existing packaging documentation (for opkg), "PROVIDES:=" is optional in the case of package jq. The old way was more forgiving. The new way is more rigid and strict.

So if you remove "PROVIDES:=jq", make package/install will succeed. And the contents of "staging_dir/target-aarch64_cortex-a53_musl/pkginfo/jq.provides"  are exactly same before and after.

**Comment by efahl** [comment]
> This is built with my latest patcheset. What am I missing here?

The libreadline is built using the sanitized dependency name:
```
$ ~/openwrt/openwrt/staging_dir/host/bin/apk adbdump ./bin/packages/x86_64/base/libreadline*k | head -20
#%SCHEMA: 676B6370
# ADB block, size: 2200, compat: 0, ver: 0
info:
  name: libreadline8
  version: 8.3-r1
...
  installed-size: 341237
  depends: # 2 items
    - libc
    - libncursesw            <<< Not in "provides", came directly from Makefile
  provides: # 1 items
    - libreadline
  tags: # 1 items
```

So when `make world` gets to `apk add`, it fails to find the dependency:
```
IPKG_INSTROOT=/home/efahlgren/openwrt/openwrt/build_dir/target-x86_64_musl/root-x86 /home/efahlgren/openwrt/openwrt/staging_dir/host/bin/fakeroot /home/efahlgren/openwrt/openwrt/staging_dir/host/bin/apk --root /home/efahlgren/openwrt/openwrt/build_dir/target-x86_64_musl/root-x86 --keys-dir /home/efahlgren/openwrt/openwrt --no-logfile --preserve-env add --no-cache --initdb --no-scripts --arch x86_64 \
	--repositories-file /dev/null --repository file:///home/efahlgren/openwrt/openwrt/staging_dir/packages/x86/packages.adb \
	 \
	$(cat /home/efahlgren/openwrt/openwrt/tmp/apk_install_list) \
		"base-files=1678~2015a40c3871" \
		"libc=1.2.5-r5" \
		"kernel=6.12.62~8bf8cf619b9ad9d14b89d26fbd5bfa06-r1"
ERROR: unable to select packages:
  libncursesw (no such package):
    required by: libreadline8-8.3-r1[libncursesw]
```

**Comment by efahl** [comment]
Yeah, just wiped everything, git pull to current HEAD, `git apply 21288.patch` and same behavior.
```
$ ~/openwrt/openwrt/staging_dir/host/bin/apk adbdump ./bin/packages/x86_64/base/libncurses6-6.4-r3.apk | head -20
info:
  name: libncurses6
...
  provides: # 2 items
    - libncurses
    - libncursesw6=6.4-r3
  tags: # 1 items

$ ~/openwrt/openwrt/staging_dir/host/bin/apk adbdump ./bin/packages/x86_64/base/libreadline*k | head -20
info:
  name: libreadline8
...
  installed-size: 341237
  depends: # 2 items
    - libc
    - libncursesw   <<< sanitized "w" version here, but not in provides, above.
  provides: # 1 items
    - libreadline
```

**Comment by GeorgeSapkin** [comment]
Oh, there's no ABI. I see it now. I have it when building normally:

```bash
staging_dir/host/bin/apk adbdump ./bin/packages/x86_64/base/libreadline*k | head -20
#%SCHEMA: 676B6370
# ADB block, size: 2232, compat: 0, ver: 0
info:
  name: libreadline8
...
  depends: # 2 items
    - libc
    - libncursesw6
```

I'll look into it, but my gut feeling is this is the libc/libgcc all over again, i.e. it gets evaluated in the wrong order.

**Comment by GeorgeSapkin** [comment]
Yep, I can reproduce this, so it's the same issue.

**Comment by GeorgeSapkin** [comment]
@efahl I pushed a fix and a clean build seems to be working now 🐌

**Comment by efahl** [comment]
> 🐌

Yeah...

In any case, the preliminary check is looking good:
```
$ ~/openwrt/openwrt/staging_dir/host/bin/apk adbdump ./bin/packages/x86_64/base/libreadline*k | head -20
  name: libreadline8
  version: 8.3-r1
  depends: # 2 items
    - libc
    - libncursesw6
  provides: # 1 items
    - libreadline
  tags: # 1 items
    - openwrt:abiversion=8

$ ~/openwrt/openwrt/staging_dir/host/bin/apk adbdump ./bin/packages/x86_64/base/libncurses6-6.4-r3.apk | head -22
  name: libncurses6
  version: 6.4-r3
  depends: # 2 items
    - libc
    - terminfo
  provides: # 2 items
    - libncurses
    - libncursesw6=6.4-r3
  tags: # 1 items
    - openwrt:abiversion=6
```

Doing the full build right now, but given above results, I expect it to be Perfect 🤞🏼😂.

**Comment by efahl** [comment]
Still getting an incorrect kmod-r81*:
```
$ make manifest PACKAGES=kmod-r8169 | grep kmod-r

blah blah ... apk ... add --arch x86_64 --no-scripts kmod-r8169 apk-mbedtls base-files ca-bundle dnsmasq dropbear e2fsprogs firewall4 fstools grub2-bios-setup kernel kmod-amazon-ena kmod-amd-xgbe kmod-bnx2 kmod-button-hotplug kmod-drm-i915 kmod-dwmac-intel kmod-e1000 kmod-e1000e kmod-forcedeth kmod-fs-vfat kmod-igb kmod-igc kmod-ixgbe kmod-nft-offload kmod-r8169 kmod-tg3 libc libgcc libustream-mbedtls logd mkf2fs mtd netifd nftables odhcp6c odhcpd-ipv6only partx-utils ppp ppp-mod-pppoe procd-ujail uci uclient-fetch urandom-seed urngd \

  kmod-r8168 (6.12.62.8.055.00-r4)
(124/146) Installing kmod-r8168 (6.12.62.8.055.00-r4)
lib/apk/packages/kmod-r8168.list
kmod-r8168 - 6.12.62.8.055.00-r4
```

Where the packages look like this, so it appears that the `-r4` means that it's "newest", since the "base" package -very bottom of list- is just `r1`.  When I had hacked it up yesterday, I left off the rev altogether, with the provides lines all `kmod-r8169=6.12.62` and that seemed to work ok without a rev.
```
apk adbdump packages/kmod-r8* | grep -E '^  (name:|version:|provid|  - kmod-r8)'
  name: kmod-r8101
  version: 6.12.62.1.039.00-r3
  provider-priority: 1
  provides: # 1 items
    - kmod-r8169=6.12.62-r3

  name: kmod-r8125
  version: 6.12.62.9.016.01-r1
  provider-priority: 1
  provides: # 1 items
    - kmod-r8169=6.12.62-r1

  name: kmod-r8125-rss
  version: 6.12.62.9.016.01-r1
  provider-priority: 1
  provides: # 1 items
    - kmod-r8169=6.12.62-r1
  
  name: kmod-r8126
  version: 6.12.62.10.016.00-r1
  provider-priority: 1
  provides: # 1 items
    - kmod-r8169=6.12.62-r1

  name: kmod-r8126-rss
  version: 6.12.62.10.016.00-r1
  provider-priority: 1
  provides: # 1 items
    - kmod-r8169=6.12.62-r1

  name: kmod-r8127
  version: 6.12.62.11.015.00-r1
  provider-priority: 1
  provides: # 1 items
    - kmod-r8169=6.12.62-r1

  name: kmod-r8127-rss
  version: 6.12.62.11.015.00-r1
  provider-priority: 1
  provides: # 1 items
    - kmod-r8169=6.12.62-r1

  name: kmod-r8168
  version: 6.12.62.8.055.00-r4
  provider-priority: 1
  provides: # 1 items
    - kmod-r8169=6.12.62-r4

  name: kmod-r8168-rss
  version: 6.12.62.8.055.00-r4
  provider-priority: 1
  provides: # 1 items
    - kmod-r8169=6.12.62-r4

  name: kmod-r8169
  version: 6.12.62-r1
```

**Comment by efahl** [comment]
Hacking at it again...

Man, we are so close now; phenomenal work so far!

**Comment by efahl** [comment]
Confirmed that using simply the kernel version sans any package rev works properly with both apk add and imagebuilder installation.
```
 name: kmod-r8101
  version: 6.12.62.1.039.00-r3
  provider-priority: 1
  provides: # 1 items
    - kmod-r8169=6.12.62   <<< 
```

**Comment by GeorgeSapkin** [comment]
@efahl I still feel the kmod part is too janky, I'm going to try something else.

**Comment by efahl** [comment]
Yeah, I keep thinking something else will have the same pattern and the special casing isn't scalable...

So I've been digging through the packages on my Alpine laptop trying to find a similar set of packages to see how they handle things.  Grabbed all the `provides` values into a big list, then counted them.

<details><summary>Top 20 packages on Alpine Linux v3.23 x86_64</summary>

```
$ uniq -c x | sort -nr | head -20
    112 linux-firmware-any
     31 cloud-init-datasources-any
      7 cmd:emacsclient=30.2-r0
      7 cmd:emacs=30.2-r0
      7 cmd:emacs-30.2=30.2-r0
      6 libtss2-tcti
      5 lua
      5 java-jre-headless
      5 java-jre
      5 java-jdk
      4 sxmo-utils-wm
      4 postgresql-contrib
      4 postgresql-client
      4 postgresql
      4 freeciv-client
      4 dbus:org.freedesktop.Secrets
      4 cmd:dnsmasq=2.91-r0
      3 yt-dlp-ejs-rt=0.3.2-r0
      3 so:libwolfssl.so.44=44.0.0
      3 so:dotnet9:libmscordbi.so=0
```
</details>

<details><summary>No real matches, `yt-dlp` looks like our `dnsmasq`/`vim` variations.</summary>

```
$ apk query --fields package,name,version,provider-priority,provides --match provides yt-dlp-ejs-rt
Package: yt-dlp-ejs-rt-deno-0.3.2-r0
Name: yt-dlp-ejs-rt-deno
Version: 0.3.2-r0
Provider-Priority: 100
Provides: yt-dlp-ejs-rt=0.3.2-r0

Package: yt-dlp-ejs-rt-nodejs-0.3.2-r0
Name: yt-dlp-ejs-rt-nodejs
Version: 0.3.2-r0
Provider-Priority: 10
Provides: yt-dlp-ejs-rt=0.3.2-r0

Package: yt-dlp-ejs-rt-quickjs-0.3.2-r0
Name: yt-dlp-ejs-rt-quickjs
Version: 0.3.2-r0
Provider-Priority: 20
Provides: yt-dlp-ejs-rt=0.3.2-r0
```
</details>

Better match is this lib, where they use the `.so` as the versioned item, with an unversioned package name.  This seems like it might be the one:
```
$ apk query --fields package,name,version,provider-priority,depends,provides --match provides libtss2-tcti
Package: tpm2-tss-tcti-cmd-4.1.2-r0
Name: tpm2-tss-tcti-cmd
Version: 4.1.2-r0
Provider-Priority: 10
Provides: libtss2-tcti so:libtss2-tcti-cmd.so.0=0.0.0

Package: tpm2-tss-tcti-device-4.1.2-r0
Name: tpm2-tss-tcti-device
Version: 4.1.2-r0
Provider-Priority: 100
Provides: libtss2-tcti so:libtss2-tcti-device.so.0=0.0.0

Package: tpm2-tss-tcti-mssim-4.1.2-r0
Name: tpm2-tss-tcti-mssim
Version: 4.1.2-r0
Provider-Priority: 10
Provides: libtss2-tcti so:libtss2-tcti-mssim.so.0=0.0.0

... 4 more with provider-priority = 10 ...
```

**Comment by map-b** [comment]
... am I or the implicit package_name=package_version is really bad as that cannot be a virtual name and it implies that package names should be always different to the actual desired provides...??

If the package_name=version is exactly the same, are your tests confirming that apk will look at provider-priority for the tie-breaker?

**Comment by thilob** [comment]
I can reproduce the error with selecting luci-app-pbr, if it helps.

**Comment by GeorgeSapkin** [comment]
@thilob have you tried the linked PR #21288?

**Comment by egc112** [comment]
Thanks for all your work. 
For the record to compile for now I just removed the PROVIDES in `package/system/ca-certificates/Makefile` to get rid of the ca-bundle/ca-certificates error, that seems to work, but hoping for a quick implementation which you have worked out.
